<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $filas = [
            ["nombre"=>"Alto Orinoco","estado_id"=>"1","id"=>"1"],
         ["nombre"=>"Atabapo","estado_id"=>"1","id"=>"2"],
         ["nombre"=>"Atures","estado_id"=>"1","id"=>"3"],
         ["nombre"=>"Autana","estado_id"=>"1","id"=>"4"],
         ["nombre"=>"Manapiare","estado_id"=>"1","id"=>"5"],
         ["nombre"=>"Maroa","estado_id"=>"1","id"=>"6"],
         ["nombre"=>"Río Negro","estado_id"=>"1","id"=>"7"],
         ["nombre"=>"Anaco","estado_id"=>"2","id"=>"8"],
         ["nombre"=>"Aragua","estado_id"=>"2","id"=>"9"],
         ["nombre"=>"Bolívar","estado_id"=>"2","id"=>"10"],
         ["nombre"=>"Bruzual","estado_id"=>"2","id"=>"11"],
         ["nombre"=>"Cajigal","estado_id"=>"2","id"=>"12"],
         ["nombre"=>"Carvajal","estado_id"=>"2","id"=>"13"],
         ["nombre"=>"Diego Bautista Urbaneja","estado_id"=>"2","id"=>"14"],
         ["nombre"=>"Freites","estado_id"=>"2","id"=>"15"],
         ["nombre"=>"Guanipa","estado_id"=>"2","id"=>"16"],
         ["nombre"=>"Guanta","estado_id"=>"2","id"=>"17"],
         ["nombre"=>"Independencia","estado_id"=>"2","id"=>"18"],
         ["nombre"=>"Libertad","estado_id"=>"2","id"=>"19"],
         ["nombre"=>"McGregor","estado_id"=>"2","id"=>"20"],
         ["nombre"=>"Miranda","estado_id"=>"2","id"=>"21"],
         ["nombre"=>"Monagas","estado_id"=>"2","id"=>"22"],
         ["nombre"=>"Peñalver","estado_id"=>"2","id"=>"23"],
         ["nombre"=>"Píritu","estado_id"=>"2","id"=>"24"],
         ["nombre"=>"San Juan de Capistrano","estado_id"=>"2","id"=>"25"],
         ["nombre"=>"Santa Ana","estado_id"=>"2","id"=>"26"],
         ["nombre"=>"Simón Rodríguez","estado_id"=>"2","id"=>"27"],
         ["nombre"=>"Sotillo","estado_id"=>"2","id"=>"28"],
         ["nombre"=>"Achaguas","estado_id"=>"3","id"=>"29"],
         ["nombre"=>"Biruaca","estado_id"=>"3","id"=>"30"],
         ["nombre"=>"Muñoz","estado_id"=>"3","id"=>"31"],
         ["nombre"=>"Páez","estado_id"=>"3","id"=>"32"],
         ["nombre"=>"Pedro Camejo","estado_id"=>"3","id"=>"33"],
         ["nombre"=>"Rómulo Gallegos","estado_id"=>"3","id"=>"34"],
         ["nombre"=>"San Fernando","estado_id"=>"3","id"=>"35"],
         ["nombre"=>"Bolívar","estado_id"=>"4","id"=>"36"],
         ["nombre"=>"Camatagua","estado_id"=>"4","id"=>"37"],
         ["nombre"=>"Francisco Linares Alcántara","estado_id"=>"4","id"=>"38"],
         ["nombre"=>"Girardot","estado_id"=>"4","id"=>"39"],
         ["nombre"=>"José Ángel Lamas","estado_id"=>"4","id"=>"40"],
         ["nombre"=>"José Félix Ribas","estado_id"=>"4","id"=>"41"],
         ["nombre"=>"José Rafael Revenga","estado_id"=>"4","id"=>"42"],
         ["nombre"=>"Libertador","estado_id"=>"4","id"=>"43"],
         ["nombre"=>"Mario Briceño Iragorry","estado_id"=>"4","id"=>"44"],
         ["nombre"=>"Ocumare de la Costa de Oro","estado_id"=>"4","id"=>"45"],
         ["nombre"=>"San Casimiro","estado_id"=>"4","id"=>"46"],
         ["nombre"=>"San Sebastián","estado_id"=>"4","id"=>"47"],
         ["nombre"=>"Santiago Mariño","estado_id"=>"4","id"=>"48"],
         ["nombre"=>"Santos Michelena","estado_id"=>"4","id"=>"49"],
         ["nombre"=>"Sucre","estado_id"=>"4","id"=>"50"],
         ["nombre"=>"Tovar","estado_id"=>"4","id"=>"51"],
         ["nombre"=>"Urdaneta","estado_id"=>"4","id"=>"52"],
         ["nombre"=>"Zamora","estado_id"=>"4","id"=>"53"],
         ["nombre"=>"Alberto Arvelo Torrealba","estado_id"=>"5","id"=>"54"],
         ["nombre"=>"Andrés Eloy Blanco","estado_id"=>"5","id"=>"55"],
         ["nombre"=>"Antonio José de Sucre","estado_id"=>"5","id"=>"56"],
         ["nombre"=>"Arismendi","estado_id"=>"5","id"=>"57"],
         ["nombre"=>"Barinas","estado_id"=>"5","id"=>"58"],
         ["nombre"=>"Bolívar","estado_id"=>"5","id"=>"59"],
         ["nombre"=>"Cruz Paredes","estado_id"=>"5","id"=>"60"],
         ["nombre"=>"Ezequiel Zamora","estado_id"=>"5","id"=>"61"],
         ["nombre"=>"Obispos","estado_id"=>"5","id"=>"62"],
         ["nombre"=>"Pedraza","estado_id"=>"5","id"=>"63"],
         ["nombre"=>"Rojas","estado_id"=>"5","id"=>"64"],
         ["nombre"=>"Sosa","estado_id"=>"5","id"=>"65"],
         ["nombre"=>"Angostura","estado_id"=>"6","id"=>"66"],
         ["nombre"=>"Caroní","estado_id"=>"6","id"=>"67"],
         ["nombre"=>"Cedeño","estado_id"=>"6","id"=>"68"],
         ["nombre"=>"El Callao","estado_id"=>"6","id"=>"69"],
         ["nombre"=>"Gran Sabana","estado_id"=>"6","id"=>"70"],
         ["nombre"=>"Heres","estado_id"=>"6","id"=>"71"],
         ["nombre"=>"Píar","estado_id"=>"6","id"=>"72"],
         ["nombre"=>"Roscio","estado_id"=>"6","id"=>"73"],
         ["nombre"=>"Sifontes","estado_id"=>"6","id"=>"74"],
         ["nombre"=>"Sucre","estado_id"=>"6","id"=>"75"],
         ["nombre"=>"Padre Pedro Chien","estado_id"=>"6","id"=>"76"],
         ["nombre"=>"Bejuma","estado_id"=>"7","id"=>"77"],
         ["nombre"=>"Carlos Arvelo","estado_id"=>"7","id"=>"78"],
         ["nombre"=>"Diego Ibarra","estado_id"=>"7","id"=>"79"],
         ["nombre"=>"Guacara","estado_id"=>"7","id"=>"80"],
         ["nombre"=>"Mora","estado_id"=>"7","id"=>"81"],
         ["nombre"=>"Libertador","estado_id"=>"7","id"=>"82"],
         ["nombre"=>"Los Guayos","estado_id"=>"7","id"=>"83"],
         ["nombre"=>"Miranda","estado_id"=>"7","id"=>"84"],
         ["nombre"=>"Montalbán","estado_id"=>"7","id"=>"85"],
         ["nombre"=>"Naguanagua","estado_id"=>"7","id"=>"86"],
         ["nombre"=>"Puerto Cabello","estado_id"=>"7","id"=>"87"],
         ["nombre"=>"San Diego","estado_id"=>"7","id"=>"88"],
         ["nombre"=>"San Joaquín","estado_id"=>"7","id"=>"89"],
         ["nombre"=>"Valencia","estado_id"=>"7","id"=>"90"],
         ["nombre"=>"Anzoátegui","estado_id"=>"8","id"=>"91"],
         ["nombre"=>"Tinaquillo","estado_id"=>"8","id"=>"92"],
         ["nombre"=>"Girardot","estado_id"=>"8","id"=>"93"],
         ["nombre"=>"Lima Blanco","estado_id"=>"8","id"=>"94"],
         ["nombre"=>"Pao de San Juan Bautista","estado_id"=>"8","id"=>"95"],
         ["nombre"=>"Ricaurte","estado_id"=>"8","id"=>"96"],
         ["nombre"=>"Rómulo Gallegos","estado_id"=>"8","id"=>"97"],
         ["nombre"=>"San Carlos","estado_id"=>"8","id"=>"98"],
         ["nombre"=>"Tinaco","estado_id"=>"8","id"=>"99"],
         ["nombre"=>"Antonio Díaz","estado_id"=>"9","id"=>"100"],
         ["nombre"=>"Casacoima","estado_id"=>"9","id"=>"101"],
         ["nombre"=>"Pedernales","estado_id"=>"9","id"=>"102"],
         ["nombre"=>"Tucupita","estado_id"=>"9","id"=>"103"],
         ["nombre"=>"Acosta","estado_id"=>"10","id"=>"104"],
         ["nombre"=>"Bolívar","estado_id"=>"10","id"=>"105"],
         ["nombre"=>"Buchivacoa","estado_id"=>"10","id"=>"106"],
         ["nombre"=>"Carirubana","estado_id"=>"10","id"=>"107"],
         ["nombre"=>"Colina","estado_id"=>"10","id"=>"108"],
         ["nombre"=>"Dabajuro","estado_id"=>"10","id"=>"109"],
         ["nombre"=>"Democracia","estado_id"=>"10","id"=>"110"],
         ["nombre"=>"Falcón","estado_id"=>"10","id"=>"111"],
         ["nombre"=>"Federación","estado_id"=>"10","id"=>"112"],
         ["nombre"=>"Jacura","estado_id"=>"10","id"=>"113"],
         ["nombre"=>"Los Taques","estado_id"=>"10","id"=>"114"],
         ["nombre"=>"Manaure","estado_id"=>"10","id"=>"115"],
         ["nombre"=>"Mauroa","estado_id"=>"10","id"=>"116"],
         ["nombre"=>"Miranda","estado_id"=>"10","id"=>"117"],
         ["nombre"=>"Monseñor Iturriza","estado_id"=>"10","id"=>"118"],
         ["nombre"=>"Palmasola","estado_id"=>"10","id"=>"119"],
         ["nombre"=>"Petit","estado_id"=>"10","id"=>"120"],
         ["nombre"=>"Píritu","estado_id"=>"10","id"=>"121"],
         ["nombre"=>"San Francisco","estado_id"=>"10","id"=>"122"],
         ["nombre"=>"Sucre","estado_id"=>"10","id"=>"123"],
         ["nombre"=>"Silva","estado_id"=>"10","id"=>"124"],
         ["nombre"=>"Tocópero","estado_id"=>"10","id"=>"125"],
         ["nombre"=>"Unión","estado_id"=>"10","id"=>"126"],
         ["nombre"=>"Urumaco","estado_id"=>"10","id"=>"127"],
         ["nombre"=>"Zamora","estado_id"=>"10","id"=>"128"],
         ["nombre"=>"Camaguán","estado_id"=>"11","id"=>"129"],
         ["nombre"=>"Chaguaramas","estado_id"=>"11","id"=>"130"],
         ["nombre"=>"El Socorro","estado_id"=>"11","id"=>"131"],
         ["nombre"=>"Infante","estado_id"=>"11","id"=>"132"],
         ["nombre"=>"Las Mercedes","estado_id"=>"11","id"=>"133"],
         ["nombre"=>"Mellado","estado_id"=>"11","id"=>"134"],
         ["nombre"=>"Miranda","estado_id"=>"11","id"=>"135"],
         ["nombre"=>"Monagas","estado_id"=>"11","id"=>"136"],
         ["nombre"=>"Ortiz","estado_id"=>"11","id"=>"137"],
         ["nombre"=>"Ribas","estado_id"=>"11","id"=>"138"],
         ["nombre"=>"Roscio","estado_id"=>"11","id"=>"139"],
         ["nombre"=>"San Gerónimo de Guayabal","estado_id"=>"11","id"=>"140"],
         ["nombre"=>"San José de Guaribe","estado_id"=>"11","id"=>"141"],
         ["nombre"=>"Santa María de Ipire","estado_id"=>"11","id"=>"142"],
         ["nombre"=>"Zaraza","estado_id"=>"11","id"=>"143"],
         ["nombre"=>"Andrés Eloy Blanco","estado_id"=>"12","id"=>"144"],
         ["nombre"=>"Crespo","estado_id"=>"12","id"=>"145"],
         ["nombre"=>"Iribarren","estado_id"=>"12","id"=>"146"],
         ["nombre"=>"Jiménez","estado_id"=>"12","id"=>"147"],
         ["nombre"=>"Morán","estado_id"=>"12","id"=>"148"],
         ["nombre"=>"Palavecino","estado_id"=>"12","id"=>"149"],
         ["nombre"=>"Simón Planas","estado_id"=>"12","id"=>"150"],
         ["nombre"=>"Torres","estado_id"=>"12","id"=>"151"],
         ["nombre"=>"Urdaneta","estado_id"=>"12","id"=>"152"],
         ["nombre"=>"Alberto Adriani","estado_id"=>"13","id"=>"153"],
         ["nombre"=>"Andrés Bello","estado_id"=>"13","id"=>"154"],
         ["nombre"=>"Antonio Pinto Salinas","estado_id"=>"13","id"=>"155"],
         ["nombre"=>"Aricagua","estado_id"=>"13","id"=>"156"],
         ["nombre"=>"Arzobispo Chacón","estado_id"=>"13","id"=>"157"],
         ["nombre"=>"Campo Elías","estado_id"=>"13","id"=>"158"],
         ["nombre"=>"Caracciolo Parra Olmedo","estado_id"=>"13","id"=>"159"],
         ["nombre"=>"Cardenal Quintero","estado_id"=>"13","id"=>"160"],
         ["nombre"=>"Guaraque","estado_id"=>"13","id"=>"161"],
         ["nombre"=>"Julio César Salas","estado_id"=>"13","id"=>"162"],
         ["nombre"=>"Justo Briceño","estado_id"=>"13","id"=>"163"],
         ["nombre"=>"Libertador","estado_id"=>"13","id"=>"164"],
         ["nombre"=>"Miranda","estado_id"=>"13","id"=>"165"],
         ["nombre"=>"Obispo Ramos de Lora","estado_id"=>"13","id"=>"166"],
         ["nombre"=>"Padre Noguera","estado_id"=>"13","id"=>"167"],
         ["nombre"=>"Pueblo Llano","estado_id"=>"13","id"=>"168"],
         ["nombre"=>"Rangel","estado_id"=>"13","id"=>"169"],
         ["nombre"=>"Rivas Dávila","estado_id"=>"13","id"=>"170"],
         ["nombre"=>"Santos Marquina","estado_id"=>"13","id"=>"171"],
         ["nombre"=>"Sucre","estado_id"=>"13","id"=>"172"],
         ["nombre"=>"Tovar","estado_id"=>"13","id"=>"173"],
         ["nombre"=>"Tulio Febres Cordero","estado_id"=>"13","id"=>"174"],
         ["nombre"=>"Zea","estado_id"=>"13","id"=>"175"],
         ["nombre"=>"Acevedo","estado_id"=>"14","id"=>"176"],
         ["nombre"=>"Andrés Bello","estado_id"=>"14","id"=>"177"],
         ["nombre"=>"Baruta","estado_id"=>"14","id"=>"178"],
         ["nombre"=>"Brión","estado_id"=>"14","id"=>"179"],
         ["nombre"=>"Buroz","estado_id"=>"14","id"=>"180"],
         ["nombre"=>"Carrizal","estado_id"=>"14","id"=>"181"],
         ["nombre"=>"Chacao","estado_id"=>"14","id"=>"182"],
         ["nombre"=>"Cristóbal Rojas","estado_id"=>"14","id"=>"183"],
         ["nombre"=>"El Hatillo","estado_id"=>"14","id"=>"184"],
         ["nombre"=>"Guaicaipuro","estado_id"=>"14","id"=>"185"],
         ["nombre"=>"Independencia","estado_id"=>"14","id"=>"186"],
         ["nombre"=>"Lander","estado_id"=>"14","id"=>"187"],
         ["nombre"=>"Los Salias","estado_id"=>"14","id"=>"188"],
         ["nombre"=>"Páez","estado_id"=>"14","id"=>"189"],
         ["nombre"=>"Paz Castillo","estado_id"=>"14","id"=>"190"],
         ["nombre"=>"Pedro Gual","estado_id"=>"14","id"=>"191"],
         ["nombre"=>"Plaza","estado_id"=>"14","id"=>"192"],
         ["nombre"=>"Simón Bolívar","estado_id"=>"14","id"=>"193"],
         ["nombre"=>"Sucre","estado_id"=>"14","id"=>"194"],
         ["nombre"=>"Urdaneta","estado_id"=>"14","id"=>"195"],
         ["nombre"=>"Zamora","estado_id"=>"14","id"=>"196"],
         ["nombre"=>"Acosta","estado_id"=>"15","id"=>"197"],
         ["nombre"=>"Aguasay","estado_id"=>"15","id"=>"198"],
         ["nombre"=>"Bolívar","estado_id"=>"15","id"=>"199"],
         ["nombre"=>"Caripe","estado_id"=>"15","id"=>"200"],
         ["nombre"=>"Cedeño","estado_id"=>"15","id"=>"201"],
         ["nombre"=>"Ezequiel Zamora","estado_id"=>"15","id"=>"202"],
         ["nombre"=>"Libertador","estado_id"=>"15","id"=>"203"],
         ["nombre"=>"Maturín","estado_id"=>"15","id"=>"204"],
         ["nombre"=>"Piar","estado_id"=>"15","id"=>"205"],
         ["nombre"=>"Punceres","estado_id"=>"15","id"=>"206"],
         ["nombre"=>"Santa Bárbara","estado_id"=>"15","id"=>"207"],
         ["nombre"=>"Sotillo","estado_id"=>"15","id"=>"208"],
         ["nombre"=>"Uracoa","estado_id"=>"15","id"=>"209"],
         ["nombre"=>"Antolín del Campo","estado_id"=>"16","id"=>"210"],
         ["nombre"=>"Arismendi","estado_id"=>"16","id"=>"211"],
         ["nombre"=>"Díaz","estado_id"=>"16","id"=>"212"],
         ["nombre"=>"García","estado_id"=>"16","id"=>"213"],
         ["nombre"=>"Gómez","estado_id"=>"16","id"=>"214"],
         ["nombre"=>"Maneiro","estado_id"=>"16","id"=>"215"],
         ["nombre"=>"Marcano","estado_id"=>"16","id"=>"216"],
         ["nombre"=>"Mariño","estado_id"=>"16","id"=>"217"],
         ["nombre"=>"Península de Macanao","estado_id"=>"16","id"=>"218"],
         ["nombre"=>"Tubores","estado_id"=>"16","id"=>"219"],
         ["nombre"=>"Villalba","estado_id"=>"16","id"=>"220"],
         ["nombre"=>"Agua Blanca","estado_id"=>"17","id"=>"221"],
         ["nombre"=>"Araure","estado_id"=>"17","id"=>"222"],
         ["nombre"=>"Esteller","estado_id"=>"17","id"=>"223"],
         ["nombre"=>"Guanare","estado_id"=>"17","id"=>"224"],
         ["nombre"=>"Guanarito","estado_id"=>"17","id"=>"225"],
         ["nombre"=>"Monseñor José Vicente de Unda","estado_id"=>"17","id"=>"226"],
         ["nombre"=>"Ospino","estado_id"=>"17","id"=>"227"],
         ["nombre"=>"Páez","estado_id"=>"17","id"=>"228"],
         ["nombre"=>"Papelón","estado_id"=>"17","id"=>"229"],
         ["nombre"=>"San Genaro de Boconoíto","estado_id"=>"17","id"=>"230"],
         ["nombre"=>"San Rafael de Onoto","estado_id"=>"17","id"=>"231"],
         ["nombre"=>"Santa Rosalía","estado_id"=>"17","id"=>"232"],
         ["nombre"=>"Sucre","estado_id"=>"17","id"=>"233"],
         ["nombre"=>"Turén","estado_id"=>"17","id"=>"234"],
         ["nombre"=>"Andrés Eloy Blanco","estado_id"=>"18","id"=>"235"],
         ["nombre"=>"Andrés Mata","estado_id"=>"18","id"=>"236"],
         ["nombre"=>"Arismendi","estado_id"=>"18","id"=>"237"],
         ["nombre"=>"Benítez","estado_id"=>"18","id"=>"238"],
         ["nombre"=>"Bermúdez","estado_id"=>"18","id"=>"239"],
         ["nombre"=>"Bolívar","estado_id"=>"18","id"=>"240"],
         ["nombre"=>"Cajigal","estado_id"=>"18","id"=>"241"],
         ["nombre"=>"Cruz Salmerón Acosta","estado_id"=>"18","id"=>"242"],
         ["nombre"=>"Libertador","estado_id"=>"18","id"=>"243"],
         ["nombre"=>"Mariño","estado_id"=>"18","id"=>"244"],
         ["nombre"=>"Mejía","estado_id"=>"18","id"=>"245"],
         ["nombre"=>"Montes","estado_id"=>"18","id"=>"246"],
         ["nombre"=>"Ribero","estado_id"=>"18","id"=>"247"],
         ["nombre"=>"Sucre","estado_id"=>"18","id"=>"248"],
         ["nombre"=>"Valdez","estado_id"=>"18","id"=>"249"],
         ["nombre"=>"Andrés Bello","estado_id"=>"19","id"=>"250"],
         ["nombre"=>"Antonio Rómulo Costa","estado_id"=>"19","id"=>"251"],
         ["nombre"=>"Ayacucho","estado_id"=>"19","id"=>"252"],
         ["nombre"=>"Bolívar","estado_id"=>"19","id"=>"253"],
         ["nombre"=>"Cárdenas","estado_id"=>"19","id"=>"254"],
         ["nombre"=>"Córdoba","estado_id"=>"19","id"=>"255"],
         ["nombre"=>"Fernández Feo","estado_id"=>"19","id"=>"256"],
         ["nombre"=>"Francisco de Miranda","estado_id"=>"19","id"=>"257"],
         ["nombre"=>"García de Hevia","estado_id"=>"19","id"=>"258"],
         ["nombre"=>"Guásimos","estado_id"=>"19","id"=>"259"],
         ["nombre"=>"Independencia","estado_id"=>"19","id"=>"260"],
         ["nombre"=>"Jáuregui","estado_id"=>"19","id"=>"261"],
         ["nombre"=>"José María Vargas","estado_id"=>"19","id"=>"262"],
         ["nombre"=>"Junín","estado_id"=>"19","id"=>"263"],
         ["nombre"=>"Libertad","estado_id"=>"19","id"=>"264"],
         ["nombre"=>"Libertador","estado_id"=>"19","id"=>"265"],
         ["nombre"=>"Lobatera","estado_id"=>"19","id"=>"266"],
         ["nombre"=>"Michelena","estado_id"=>"19","id"=>"267"],
         ["nombre"=>"Panamericano","estado_id"=>"19","id"=>"268"],
         ["nombre"=>"Pedro María Ureña","estado_id"=>"19","id"=>"269"],
         ["nombre"=>"Rafael Urdaneta","estado_id"=>"19","id"=>"270"],
         ["nombre"=>"Samuel Darío Maldonado","estado_id"=>"19","id"=>"271"],
         ["nombre"=>"San Cristóbal","estado_id"=>"19","id"=>"272"],
         ["nombre"=>"Seboruco","estado_id"=>"19","id"=>"273"],
         ["nombre"=>"Simón Rodríguez","estado_id"=>"19","id"=>"274"],
         ["nombre"=>"Sucre","estado_id"=>"19","id"=>"275"],
         ["nombre"=>"Torbes","estado_id"=>"19","id"=>"276"],
         ["nombre"=>"Uribante","estado_id"=>"19","id"=>"277"],
         ["nombre"=>"San Judas Tadeo","estado_id"=>"19","id"=>"278"],
         ["nombre"=>"Andrés Bello","estado_id"=>"20","id"=>"279"],
         ["nombre"=>"Boconó","estado_id"=>"20","id"=>"280"],
         ["nombre"=>"Bolívar","estado_id"=>"20","id"=>"281"],
         ["nombre"=>"Candelaria","estado_id"=>"20","id"=>"282"],
         ["nombre"=>"Carache","estado_id"=>"20","id"=>"283"],
         ["nombre"=>"Escuque","estado_id"=>"20","id"=>"284"],
         ["nombre"=>"José Felipe Márquez Cañizalez","estado_id"=>"20","id"=>"285"],
         ["nombre"=>"Juan Vicente Campos Elías","estado_id"=>"20","id"=>"286"],
         ["nombre"=>"La Ceiba","estado_id"=>"20","id"=>"287"],
         ["nombre"=>"Miranda","estado_id"=>"20","id"=>"288"],
         ["nombre"=>"Monte Carmelo","estado_id"=>"20","id"=>"289"],
         ["nombre"=>"Motatán","estado_id"=>"20","id"=>"290"],
         ["nombre"=>"Pampán","estado_id"=>"20","id"=>"291"],
         ["nombre"=>"Pampanito","estado_id"=>"20","id"=>"292"],
         ["nombre"=>"Rafael Rangel","estado_id"=>"20","id"=>"293"],
         ["nombre"=>"San Rafael de Carvajal","estado_id"=>"20","id"=>"294"],
         ["nombre"=>"Sucre","estado_id"=>"20","id"=>"295"],
         ["nombre"=>"Trujillo","estado_id"=>"20","id"=>"296"],
         ["nombre"=>"Urdaneta","estado_id"=>"20","id"=>"297"],
         ["nombre"=>"Valera","estado_id"=>"20","id"=>"298"],
         ["nombre"=>"Vargas","estado_id"=>"21","id"=>"299"],
         ["nombre"=>"Arístides Bastidas","estado_id"=>"22","id"=>"300"],
         ["nombre"=>"Bolívar","estado_id"=>"22","id"=>"301"],
         ["nombre"=>"Bruzual","estado_id"=>"22","id"=>"302"],
         ["nombre"=>"Cocorote","estado_id"=>"22","id"=>"303"],
         ["nombre"=>"Independencia","estado_id"=>"22","id"=>"304"],
         ["nombre"=>"José Antonio Páez","estado_id"=>"22","id"=>"305"],
         ["nombre"=>"La Trinidad","estado_id"=>"22","id"=>"306"],
         ["nombre"=>"Manuel Monge","estado_id"=>"22","id"=>"307"],
         ["nombre"=>"Nirgua","estado_id"=>"22","id"=>"308"],
         ["nombre"=>"Peña","estado_id"=>"22","id"=>"309"],
         ["nombre"=>"San Felipe","estado_id"=>"22","id"=>"310"],
         ["nombre"=>"Sucre","estado_id"=>"22","id"=>"311"],
         ["nombre"=>"Urachiche","estado_id"=>"22","id"=>"312"],
         ["nombre"=>"Veroes","estado_id"=>"22","id"=>"313"],
         ["nombre"=>"Almirante Padilla","estado_id"=>"23","id"=>"314"],
         ["nombre"=>"Baralt","estado_id"=>"23","id"=>"315"],
         ["nombre"=>"Cabimas","estado_id"=>"23","id"=>"316"],
         ["nombre"=>"Catatumbo","estado_id"=>"23","id"=>"317"],
         ["nombre"=>"Colón","estado_id"=>"23","id"=>"318"],
         ["nombre"=>"Francisco Javier Pulgar","estado_id"=>"23","id"=>"319"],
         ["nombre"=>"Páez","estado_id"=>"23","id"=>"320"],
         ["nombre"=>"Jesús Enrique Lossada","estado_id"=>"23","id"=>"321"],
         ["nombre"=>"Jesús María Semprún","estado_id"=>"23","id"=>"322"],
         ["nombre"=>"La Cañada de Urdaneta","estado_id"=>"23","id"=>"323"],
         ["nombre"=>"Lagunillas","estado_id"=>"23","id"=>"324"],
         ["nombre"=>"Machiques de Perijá","estado_id"=>"23","id"=>"325"],
         ["nombre"=>"Mara","estado_id"=>"23","id"=>"326"],
         ["nombre"=>"Maracaibo","estado_id"=>"23","id"=>"327"],
         ["nombre"=>"Miranda","estado_id"=>"23","id"=>"328"],
         ["nombre"=>"Rosario de Perijá","estado_id"=>"23","id"=>"329"],
         ["nombre"=>"San Francisco","estado_id"=>"23","id"=>"330"],
         ["nombre"=>"Santa Rita","estado_id"=>"23","id"=>"331"],
         ["nombre"=>"Simón Bolívar","estado_id"=>"23","id"=>"332"],
         ["nombre"=>"Sucre","estado_id"=>"23","id"=>"333"],
         ["nombre"=>"Valmore Rodríguez","estado_id"=>"23","id"=>"334"],
         ["nombre"=>"Libertador","estado_id"=>"24","id"=>"335"]
     ];	

     foreach ($filas as $fila){
         Municipio::create($fila);
     }
    }
}
