<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Parroquia;

class ParroquiaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $filas = [
            ["nombre"=>"Alto Orinoco La Esmeralda","municipio_id"=>"1"],
			["nombre"=>"Huachamacare Acanaña","municipio_id"=>"1"],
			["nombre"=>"Marawaka Toky Shamanaña","municipio_id"=>"1"],
			["nombre"=>"Mavaka Mavaka","municipio_id"=>"1"],
			["nombre"=>"Sierra Parima Parimabé","municipio_id"=>"1"],
			["nombre"=>"Ucata Laja Lisa","municipio_id"=>"2"],
			["nombre"=>"Yapacana Macuruco","municipio_id"=>"2"],
			["nombre"=>"Caname Guarinuma","municipio_id"=>"2"],
			["nombre"=>"Fernando Girón Tovar","municipio_id"=>"3"],
			["nombre"=>"Luis Alberto Gómez","municipio_id"=>"3"],
			["nombre"=>"Pahueña Limón de Parhueña","municipio_id"=>"3"],
			["nombre"=>"Platanillal Platanillal","municipio_id"=>"3"],
			["nombre"=>"Samariapo Samariapo","municipio_id"=>"4"],
			["nombre"=>"Sipapo Pendare","municipio_id"=>"4"],
			["nombre"=>"Munduapo Munduapo","municipio_id"=>"4"],
			["nombre"=>"Guayapo San Pedro del Orinoco","municipio_id"=>"4"],
			["nombre"=>"Alto Ventuari Cacurí","municipio_id"=>"5"],
			["nombre"=>"Medio Ventuari Manami","municipio_id"=>"5"],
			["nombre"=>"Bajo Ventuari Marueta","municipio_id"=>"5"],
			["nombre"=>"Victorino","municipio_id"=>"6"],
			["nombre"=>"Comunidad","municipio_id"=>"6"],
			["nombre"=>"Casiquiare Curimacare","municipio_id"=>"7"],
			["nombre"=>"Cocuy","municipio_id"=>"7"],
			["nombre"=>"San Carlos de Río Negro","municipio_id"=>"7"],
			["nombre"=>"Solano Solano","municipio_id"=>"7"],
			["nombre"=>"Anaco","municipio_id"=>"8"],
			["nombre"=>"San Joaquín","municipio_id"=>"8"],
			["nombre"=>"Cachipo","municipio_id"=>"9"],
			["nombre"=>"Aragua de Barcelona","municipio_id"=>"9"],
			["nombre"=>"Bergatín","municipio_id"=>"10"],
			["nombre"=>"Caigua","municipio_id"=>"10"],
			["nombre"=>"El Carmen.","municipio_id"=>"10"],
			["nombre"=>"El Pilar","municipio_id"=>"10"],
			["nombre"=>"Naricual.","municipio_id"=>"10"],
			["nombre"=>"San Cristóbal","municipio_id"=>"10"],
			["nombre"=>"Clarines","municipio_id"=>"11"],
			["nombre"=>"Guanape","municipio_id"=>"11"],
			["nombre"=>"Sabana de Uchire","municipio_id"=>"11"],
			["nombre"=>"Onoto","municipio_id"=>"12"],
			["nombre"=>"San Pablo","municipio_id"=>"12"],
			["nombre"=>"Valle de Guanape","municipio_id"=>"13"],
			["nombre"=>"Santa Bárbara","municipio_id"=>"13"],
			["nombre"=>"Lechería","municipio_id"=>"14"],
			["nombre"=>"El Morro","municipio_id"=>"14"],
			["nombre"=>"Cantaura","municipio_id"=>"15"],
			["nombre"=>"Libertador","municipio_id"=>"15"],
			["nombre"=>"Santa Rosa","municipio_id"=>"15"],
			["nombre"=>"Urica","municipio_id"=>"15"],
			["nombre"=>"San José de Guanipa","municipio_id"=>"16"],
			["nombre"=>"Guanta","municipio_id"=>"17"],
			["nombre"=>"Chorrerón","municipio_id"=>"17"],
			["nombre"=>"Mamo","municipio_id"=>"18"],
			["nombre"=>"Soledad","municipio_id"=>"18"],
			["nombre"=>"San Mateo","municipio_id"=>"19"],
			["nombre"=>"El Carito","municipio_id"=>"19"],
			["nombre"=>"Santa Inés","municipio_id"=>"19"],
			["nombre"=>"La Romereña","municipio_id"=>"19"],
			["nombre"=>"El Chaparro","municipio_id"=>"20"],
			["nombre"=>"Tomás Alfaro","municipio_id"=>"20"],
			["nombre"=>"Calatrava","municipio_id"=>"20"],
			["nombre"=>"Atapirire","municipio_id"=>"21"],
			["nombre"=>"Boca del Pao","municipio_id"=>"21"],
			["nombre"=>"El Pao","municipio_id"=>"21"],
			["nombre"=>"Pariaguán","municipio_id"=>"21"],
			["nombre"=>"Mapire","municipio_id"=>"22"],
			["nombre"=>"Piar","municipio_id"=>"22"],
			["nombre"=>"Santa Clara","municipio_id"=>"22"],
			["nombre"=>"San Diego de Cabrutica","municipio_id"=>"22"],
			["nombre"=>"Uverito","municipio_id"=>"22"],
			["nombre"=>"Zuata","municipio_id"=>"22"],
			["nombre"=>"Puerto Píritu","municipio_id"=>"23"],
			["nombre"=>"San Miguel","municipio_id"=>"23"],
			["nombre"=>"Sucre","municipio_id"=>"23"],
			["nombre"=>"Píritu","municipio_id"=>"24"],
			["nombre"=>"San Francisco","municipio_id"=>"24"],
			["nombre"=>"Boca de Uchire","municipio_id"=>"25"],
			["nombre"=>"Boca de Chávez","municipio_id"=>"25"],
			["nombre"=>"Pueblo Nuevo","municipio_id"=>"26"],
			["nombre"=>"Santa Ana","municipio_id"=>"26"],
			["nombre"=>"Edmundo Barrios","municipio_id"=>"27"],
			["nombre"=>"Miguel Otero Silva","municipio_id"=>"27"],
			["nombre"=>"Puerto La Cruz","municipio_id"=>"28"],
			["nombre"=>"Pozuelos","municipio_id"=>"28"],
			["nombre"=>"Achaguas","municipio_id"=>"29"],
			["nombre"=>"Apurito","municipio_id"=>"29"],
			["nombre"=>"El Yagual","municipio_id"=>"29"],
			["nombre"=>"Guachara","municipio_id"=>"29"],
			["nombre"=>"Mucuritas","municipio_id"=>"29"],
			["nombre"=>"Queseras del medio","municipio_id"=>"29"],
			["nombre"=>"Biruaca","municipio_id"=>"30"],
			["nombre"=>"Bruzual","municipio_id"=>"31"],
			["nombre"=>"Mantecal","municipio_id"=>"31"],
			["nombre"=>"Quintero","municipio_id"=>"31"],
			["nombre"=>"Rincón Hondo","municipio_id"=>"31"],
			["nombre"=>"San Vicente","municipio_id"=>"31"],
			["nombre"=>"Guasdualito","municipio_id"=>"32"],
			["nombre"=>"Aramendi","municipio_id"=>"32"],
			["nombre"=>"El Amparo","municipio_id"=>"32"],
			["nombre"=>"San Camilo","municipio_id"=>"32"],
			["nombre"=>"Urdaneta","municipio_id"=>"32"],
			["nombre"=>"San Juan de Payara","municipio_id"=>"33"],
			["nombre"=>"Codazzi","municipio_id"=>"33"],
			["nombre"=>"Cunaviche","municipio_id"=>"33"],
			["nombre"=>"Elorza","municipio_id"=>"34"],
			["nombre"=>"La Trinidad","municipio_id"=>"34"],
			["nombre"=>"San Fernando","municipio_id"=>"35"],
			["nombre"=>"El Recreo","municipio_id"=>"35"],
			["nombre"=>"Peñalver","municipio_id"=>"35"],
			["nombre"=>"San Rafael de Atamaica","municipio_id"=>"35"],
			["nombre"=>"Bolívar","municipio_id"=>"36"],
			["nombre"=>"Camatagua","municipio_id"=>"37"],
			["nombre"=>"Carmen de Cura","municipio_id"=>"37"],
			["nombre"=>"Santa Rita","municipio_id"=>"38"],
			["nombre"=>"Francisco de Miranda","municipio_id"=>"38"],
			["nombre"=>"Moseñor Feliciano González","municipio_id"=>"38"],
			["nombre"=>"Pedro José Ovalles","municipio_id"=>"39"],
			["nombre"=>"Joaquín Crespo","municipio_id"=>"39"],
			["nombre"=>"José Casanova Godoy","municipio_id"=>"39"],
			["nombre"=>"Madre María de San José","municipio_id"=>"39"],
			["nombre"=>"Andrés Eloy Blanco","municipio_id"=>"39"],
			["nombre"=>"Los Tacarigua","municipio_id"=>"39"],
			["nombre"=>"Las Delicias","municipio_id"=>"39"],
			["nombre"=>"Choroní","municipio_id"=>"39"],
			["nombre"=>"Santa Cruz","municipio_id"=>"40"],
			["nombre"=>"José Félix Ribas","municipio_id"=>"41"],
			["nombre"=>"Castor Nieves Ríos","municipio_id"=>"41"],
			["nombre"=>"Las Guacamayas","municipio_id"=>"41"],
			["nombre"=>"Pao de Zárate","municipio_id"=>"41"],
			["nombre"=>"Zuata","municipio_id"=>"41"],
			["nombre"=>"José Rafael Revenga","municipio_id"=>"42"],
			["nombre"=>"Palo Negro","municipio_id"=>"43"],
			["nombre"=>"San Martín de Porres","municipio_id"=>"43"],
			["nombre"=>"El Limón","municipio_id"=>"44"],
			["nombre"=>"Caña de Azúcar","municipio_id"=>"44"],
			["nombre"=>"Ocumare de la Costa","municipio_id"=>"45"],
			["nombre"=>"San Casimiro","municipio_id"=>"46"],
			["nombre"=>"Güiripa","municipio_id"=>"46"],
			["nombre"=>"Ollas de Caramacate","municipio_id"=>"46"],
			["nombre"=>"Valle Morín","municipio_id"=>"46"],
			["nombre"=>"San Sebastián","municipio_id"=>"47"],
			["nombre"=>"Turmero","municipio_id"=>"48"],
			["nombre"=>"Arevalo Aponte","municipio_id"=>"48"],
			["nombre"=>"Chuao","municipio_id"=>"48"],
			["nombre"=>"Samán de Güere","municipio_id"=>"48"],
			["nombre"=>"Alfredo Pacheco Miranda","municipio_id"=>"48"],
			["nombre"=>"Santos Michelena","municipio_id"=>"49"],
			["nombre"=>"Tiara","municipio_id"=>"49"],
			["nombre"=>"Cagua","municipio_id"=>"50"],
			["nombre"=>"Bella Vista","municipio_id"=>"50"],
			["nombre"=>"Tovar","municipio_id"=>"51"],
			["nombre"=>"Urdaneta","municipio_id"=>"52"],
			["nombre"=>"Las Peñitas","municipio_id"=>"52"],
			["nombre"=>"San Francisco de Cara","municipio_id"=>"52"],
			["nombre"=>"Taguay","municipio_id"=>"52"],
			["nombre"=>"Zamora","municipio_id"=>"53"],
			["nombre"=>"Magdaleno","municipio_id"=>"53"],
			["nombre"=>"San Francisco de Asís","municipio_id"=>"53"],
			["nombre"=>"Valles de Tucutunemo","municipio_id"=>"53"],
			["nombre"=>"Augusto Mijares","municipio_id"=>"53"],
			["nombre"=>"Sabaneta","municipio_id"=>"54"],
			["nombre"=>"Juan Antonio Rodríguez Domínguez","municipio_id"=>"54"],
			["nombre"=>"El Cantón","municipio_id"=>"55"],
			["nombre"=>"Santa Cruz de Guacas","municipio_id"=>"55"],
			["nombre"=>"Puerto Vivas","municipio_id"=>"55"],
			["nombre"=>"Ticoporo","municipio_id"=>"56"],
			["nombre"=>"Nicolás Pulido","municipio_id"=>"56"],
			["nombre"=>"Andrés Bello","municipio_id"=>"56"],
			["nombre"=>"Arismendi","municipio_id"=>"57"],
			["nombre"=>"Guadarrama","municipio_id"=>"57"],
			["nombre"=>"La Unión","municipio_id"=>"57"],
			["nombre"=>"San Antonio","municipio_id"=>"57"],
			["nombre"=>"Barinas","municipio_id"=>"58"],
			["nombre"=>"Alberto Arvelo Larriva","municipio_id"=>"58"],
			["nombre"=>"San Silvestre","municipio_id"=>"58"],
			["nombre"=>"Santa Inés","municipio_id"=>"58"],
			["nombre"=>"Santa Lucía","municipio_id"=>"58"],
			["nombre"=>"Torunos","municipio_id"=>"58"],
			["nombre"=>"El Carmen","municipio_id"=>"58"],
			["nombre"=>"Rómulo Betancourt","municipio_id"=>"58"],
			["nombre"=>"Corazón de Jesús","municipio_id"=>"58"],
			["nombre"=>"Ramón Ignacio Méndez","municipio_id"=>"58"],
			["nombre"=>"Alto Barinas","municipio_id"=>"58"],
			["nombre"=>"Manuel Palacio Fajardo","municipio_id"=>"58"],
			["nombre"=>"Juan Antonio Rodríguez Domínguez","municipio_id"=>"58"],
			["nombre"=>"Dominga Ortiz de Páez","municipio_id"=>"58"],
			["nombre"=>"Barinitas","municipio_id"=>"59"],
			["nombre"=>"Altamira de Cáceres","municipio_id"=>"59"],
			["nombre"=>"Calderas","municipio_id"=>"59"],
			["nombre"=>"Barrancas","municipio_id"=>"60"],
			["nombre"=>"El Socorro","municipio_id"=>"60"],
			["nombre"=>"Mazparrito","municipio_id"=>"60"],
			["nombre"=>"Santa Bárbara","municipio_id"=>"61"],
			["nombre"=>"Pedro Briceño Méndez","municipio_id"=>"61"],
			["nombre"=>"Ramón Ignacio Méndez","municipio_id"=>"61"],
			["nombre"=>"José Ignacio del Pumar","municipio_id"=>"61"],
			["nombre"=>"Obispos","municipio_id"=>"62"],
			["nombre"=>"Los Guasimitos","municipio_id"=>"62"],
			["nombre"=>"El Real","municipio_id"=>"62"],
			["nombre"=>"La Luz","municipio_id"=>"62"],
			["nombre"=>"Ciudad Bolívia","municipio_id"=>"63"],
			["nombre"=>"José Ignacio Briceño","municipio_id"=>"63"],
			["nombre"=>"José Félix Ribas","municipio_id"=>"63"],
			["nombre"=>"Páez","municipio_id"=>"63"],
			["nombre"=>"Libertad","municipio_id"=>"64"],
			["nombre"=>"Dolores","municipio_id"=>"64"],
			["nombre"=>"Santa Rosa","municipio_id"=>"64"],
			["nombre"=>"Palacio Fajardo","municipio_id"=>"64"],
			["nombre"=>"Simón Rodríguez","municipio_id"=>"64"],
			["nombre"=>"Ciudad de Nutrias","municipio_id"=>"65"],
			["nombre"=>"El Regalo","municipio_id"=>"65"],
			["nombre"=>"Puerto Nutrias","municipio_id"=>"65"],
			["nombre"=>"Santa Catalina","municipio_id"=>"65"],
			["nombre"=>"Simón Bolívar","municipio_id"=>"65"],
			["nombre"=>"Raúl Leoni","municipio_id"=>"66"],
			["nombre"=>"Barceloneta","municipio_id"=>"66"],
			["nombre"=>"Santa Bárbara","municipio_id"=>"66"],
			["nombre"=>"San Francisco","municipio_id"=>"66"],
			["nombre"=>"Cachamay","municipio_id"=>"67"],
			["nombre"=>"Chirica","municipio_id"=>"67"],
			["nombre"=>"Dalla Costa","municipio_id"=>"67"],
			["nombre"=>"Once de Abril","municipio_id"=>"67"],
			["nombre"=>"Simón Bolívar","municipio_id"=>"67"],
			["nombre"=>"Unare","municipio_id"=>"67"],
			["nombre"=>"Universidad","municipio_id"=>"67"],
			["nombre"=>"Vista al Sol","municipio_id"=>"67"],
			["nombre"=>"Pozo Verde","municipio_id"=>"67"],
			["nombre"=>"Yocoima","municipio_id"=>"67"],
			["nombre"=>"5 de Julio","municipio_id"=>"67"],
			["nombre"=>"Cedeño","municipio_id"=>"68"],
			["nombre"=>"Altagracia","municipio_id"=>"68"],
			["nombre"=>"Ascensión Farreras","municipio_id"=>"68"],
			["nombre"=>"Guaniamo","municipio_id"=>"68"],
			["nombre"=>"La Urbana","municipio_id"=>"68"],
			["nombre"=>"Pijiguaos","municipio_id"=>"68"],
			["nombre"=>"El Callao","municipio_id"=>"69"],
			["nombre"=>"Gran Sabana","municipio_id"=>"70"],
			["nombre"=>"Ikabarú","municipio_id"=>"70"],
			["nombre"=>"Catedral","municipio_id"=>"71"],
			["nombre"=>"Zea","municipio_id"=>"71"],
			["nombre"=>"Orinoco","municipio_id"=>"71"],
			["nombre"=>"José Antonio Páez","municipio_id"=>"71"],
			["nombre"=>"Marhuanta","municipio_id"=>"71"],
			["nombre"=>"Agua Salada","municipio_id"=>"71"],
			["nombre"=>"Vista Hermosa","municipio_id"=>"71"],
			["nombre"=>"La Sabanita","municipio_id"=>"71"],
			["nombre"=>"Panapana","municipio_id"=>"71"],
			["nombre"=>"Andrés Eloy Blanco","municipio_id"=>"72"],
			["nombre"=>"Pedro Cova","municipio_id"=>"72"],
			["nombre"=>"Roscio","municipio_id"=>"73"],
			["nombre"=>"Salóm","municipio_id"=>"73"],
			["nombre"=>"Sifontes","municipio_id"=>"74"],
			["nombre"=>"Dalla Costa","municipio_id"=>"74"],
			["nombre"=>"San Isidro","municipio_id"=>"74"],
			["nombre"=>"Sucre","municipio_id"=>"75"],
			["nombre"=>"Aripao","municipio_id"=>"75"],
			["nombre"=>"Guarataro","municipio_id"=>"75"],
			["nombre"=>"Las Majadas","municipio_id"=>"75"],
			["nombre"=>"Moitaco","municipio_id"=>"75"],
			["nombre"=>"Padre Pedro Chien","municipio_id"=>"76"],
			["nombre"=>"Río Grande","municipio_id"=>"76"],
			["nombre"=>"Bejuma","municipio_id"=>"77"],
			["nombre"=>"Canoabo","municipio_id"=>"77"],
			["nombre"=>"Simón Bolívar","municipio_id"=>"77"],
			["nombre"=>"Güigüe","municipio_id"=>"78"],
			["nombre"=>"Carabobo","municipio_id"=>"78"],
			["nombre"=>"Tacarigua","municipio_id"=>"78"],
			["nombre"=>"Mariara","municipio_id"=>"79"],
			["nombre"=>"Aguas Calientes","municipio_id"=>"79"],
			["nombre"=>"Ciudad Alianza","municipio_id"=>"80"],
			["nombre"=>"Guacara","municipio_id"=>"80"],
			["nombre"=>"Yagua","municipio_id"=>"80"],
			["nombre"=>"Morón","municipio_id"=>"81"],
			["nombre"=>"Urama","municipio_id"=>"81"],
			["nombre"=>"Valencia","municipio_id"=>"82"],
			["nombre"=>"Campo Carabobo","municipio_id"=>"82"],
			["nombre"=>"Los Guayos","municipio_id"=>"83"],
			["nombre"=>"Miranda","municipio_id"=>"84"],
			["nombre"=>"Montalbán","municipio_id"=>"85"],
			["nombre"=>"Naguanagua","municipio_id"=>"86"],
			["nombre"=>"Bartolomé Salóm","municipio_id"=>"87"],
			["nombre"=>"Democracia","municipio_id"=>"87"],
			["nombre"=>"Fraternidad","municipio_id"=>"87"],
			["nombre"=>"Goaigoaza","municipio_id"=>"87"],
			["nombre"=>"Juan José Flores","municipio_id"=>"87"],
			["nombre"=>"Unión","municipio_id"=>"87"],
			["nombre"=>"Borburata","municipio_id"=>"87"],
			["nombre"=>"Patanemo","municipio_id"=>"87"],
			["nombre"=>"San Diego","municipio_id"=>"88"],
			["nombre"=>"San Joaquín","municipio_id"=>"89"],
			["nombre"=>"Urbana Candelaria","municipio_id"=>"90"],
			["nombre"=>"Urbana Catedral","municipio_id"=>"90"],
			["nombre"=>"Urbana El Socorro","municipio_id"=>"90"],
			["nombre"=>"Urbana Miguel Peña","municipio_id"=>"90"],
			["nombre"=>"Urbana Rafael Urdaneta","municipio_id"=>"90"],
			["nombre"=>"Urbana San Blas","municipio_id"=>"90"],
			["nombre"=>"Urbana San José","municipio_id"=>"90"],
			["nombre"=>"Urbana Santa Rosa","municipio_id"=>"90"],
			["nombre"=>"No Urbana Negro Primero","municipio_id"=>"90"],
			["nombre"=>"Cojedes","municipio_id"=>"91"],
			["nombre"=>"Juan de Mata Suárez","municipio_id"=>"91"],
			["nombre"=>"Tinaquillo","municipio_id"=>"92"],
			["nombre"=>"El Baúl","municipio_id"=>"93"],
			["nombre"=>"Sucre","municipio_id"=>"93"],
			["nombre"=>"La Aguadita","municipio_id"=>"94"],
			["nombre"=>"Macapo","municipio_id"=>"94"],
			["nombre"=>"El Pao","municipio_id"=>"95"],
			["nombre"=>"El Amparo","municipio_id"=>"96"],
			["nombre"=>"Libertad de Cojedes","municipio_id"=>"96"],
			["nombre"=>"Rómulo Gallegos","municipio_id"=>"97"],
			["nombre"=>"San Carlos de Austria","municipio_id"=>"98"],
			["nombre"=>"Juan Ángel Bravo","municipio_id"=>"98"],
			["nombre"=>"Manuel Manrique","municipio_id"=>"98"],
			["nombre"=>"General en Jefe José Laurencio Silva","municipio_id"=>"99"],
			["nombre"=>"Curiapo","municipio_id"=>"100"],
			["nombre"=>"Almirante Luis Brión","municipio_id"=>"100"],
			["nombre"=>"Francisco Aniceto Lugo Boca de Cuyubini","municipio_id"=>"100"],
			["nombre"=>"Manuel Renaud","municipio_id"=>"100"],
			["nombre"=>"Padre Barral","municipio_id"=>"100"],
			["nombre"=>"Santos de Abelgas","municipio_id"=>"100"],
			["nombre"=>"Imataca Moruca","municipio_id"=>"101"],
			["nombre"=>"Cinco de Julio Piacoa","municipio_id"=>"101"],
			["nombre"=>"Juan Bautista Arismendi","municipio_id"=>"101"],
			["nombre"=>"Manuel Piar Santa Catalina","municipio_id"=>"101"],
			["nombre"=>"Rómulo Gallegos","municipio_id"=>"101"],
			["nombre"=>"Pedernales","municipio_id"=>"102"],
			["nombre"=>"Luis Beltrán Prieto Figueroa","municipio_id"=>"102"],
			["nombre"=>"San José","municipio_id"=>"103"],
			["nombre"=>"José Vidal Marcano Caparal de Guara","municipio_id"=>"103"],
			["nombre"=>"Juan Millán","municipio_id"=>"103"],
			["nombre"=>"Leonardo Ruíz Pineda Paloma","municipio_id"=>"103"],
			["nombre"=>"Mariscal Antonio José de Sucre","municipio_id"=>"103"],
			["nombre"=>"Monseñor Argimiro García San Rafael","municipio_id"=>"103"],
			["nombre"=>"San Rafael","municipio_id"=>"103"],
			["nombre"=>"Virgen del Valle","municipio_id"=>"103"],
			["nombre"=>"Capadare","municipio_id"=>"104"],
			["nombre"=>"La Pastora","municipio_id"=>"104"],
			["nombre"=>"Libertador","municipio_id"=>"104"],
			["nombre"=>"San Juan de los Cayos","municipio_id"=>"104"],
			["nombre"=>"Aracua","municipio_id"=>"105"],
			["nombre"=>"La Peña","municipio_id"=>"105"],
			["nombre"=>"San Luis","municipio_id"=>"105"],
			["nombre"=>"Bariro","municipio_id"=>"106"],
			["nombre"=>"Borojó","municipio_id"=>"106"],
			["nombre"=>"Capatárida","municipio_id"=>"106"],
			["nombre"=>"Guajiro","municipio_id"=>"106"],
			["nombre"=>"Seque","municipio_id"=>"106"],
			["nombre"=>"Zazárida","municipio_id"=>"106"],
			["nombre"=>"Valle de Eroa","municipio_id"=>"106"],
			["nombre"=>"Norte","municipio_id"=>"107"],
			["nombre"=>"Carirubana","municipio_id"=>"107"],
			["nombre"=>"Santa Ana","municipio_id"=>"107"],
			["nombre"=>"Urbana Punta Cardón","municipio_id"=>"107"],
			["nombre"=>"La Vela de Coro","municipio_id"=>"108"],
			["nombre"=>"Acurigua","municipio_id"=>"108"],
			["nombre"=>"Guaibacoa","municipio_id"=>"108"],
			["nombre"=>"Las Calderas","municipio_id"=>"108"],
			["nombre"=>"Macoruca","municipio_id"=>"108"],
			["nombre"=>"Dabajuro","municipio_id"=>"109"],
			["nombre"=>"Agua Clara","municipio_id"=>"110"],
			["nombre"=>"Avaria","municipio_id"=>"110"],
			["nombre"=>"Pedregal","municipio_id"=>"110"],
			["nombre"=>"Piedra Grande","municipio_id"=>"110"],
			["nombre"=>"Purureche","municipio_id"=>"110"],
			["nombre"=>"Adaure","municipio_id"=>"111"],
			["nombre"=>"Adícora","municipio_id"=>"111"],
			["nombre"=>"Baraived","municipio_id"=>"111"],
			["nombre"=>"Buena Vista","municipio_id"=>"111"],
			["nombre"=>"Jadacaquiva","municipio_id"=>"111"],
			["nombre"=>"El Vínculo","municipio_id"=>"111"],
			["nombre"=>"El Hato","municipio_id"=>"111"],
			["nombre"=>"Moruy","municipio_id"=>"111"],
			["nombre"=>"Pueblo Nuevo","municipio_id"=>"111"],
			["nombre"=>"Agua Larga","municipio_id"=>"112"],
			["nombre"=>"Churuguara","municipio_id"=>"112"],
			["nombre"=>"El Paují","municipio_id"=>"112"],
			["nombre"=>"Independencia","municipio_id"=>"112"],
			["nombre"=>"Mapararí","municipio_id"=>"112"],
			["nombre"=>"Agua Linda","municipio_id"=>"113"],
			["nombre"=>"Araurima","municipio_id"=>"113"],
			["nombre"=>"Jacura","municipio_id"=>"113"],
			["nombre"=>"Los Taques","municipio_id"=>"114"],
			["nombre"=>"Judibana","municipio_id"=>"114"],
			["nombre"=>"Cacique Manaure","municipio_id"=>"115"],
			["nombre"=>"Mene de Mauroa","municipio_id"=>"116"],
			["nombre"=>"San Félix","municipio_id"=>"116"],
			["nombre"=>"Casigua","municipio_id"=>"116"],
			["nombre"=>"Guzmán Guillermo","municipio_id"=>"117"],
			["nombre"=>"Mitare","municipio_id"=>"117"],
			["nombre"=>"Río Seco","municipio_id"=>"117"],
			["nombre"=>"Sabaneta","municipio_id"=>"117"],
			["nombre"=>"San Antonio","municipio_id"=>"117"],
			["nombre"=>"San Gabriel","municipio_id"=>"117"],
			["nombre"=>"Santa Ana","municipio_id"=>"117"],
			["nombre"=>"Boca del Tocuyo","municipio_id"=>"118"],
			["nombre"=>"Chichiriviche","municipio_id"=>"118"],
			["nombre"=>"Tocuyo de la Costa","municipio_id"=>"118"],
			["nombre"=>"Palmasola","municipio_id"=>"119"],
			["nombre"=>"Cabure","municipio_id"=>"120"],
			["nombre"=>"Colina","municipio_id"=>"120"],
			["nombre"=>"Curimagua","municipio_id"=>"120"],
			["nombre"=>"San José de la Costa","municipio_id"=>"121"],
			["nombre"=>"Píritu","municipio_id"=>"121"],
			["nombre"=>"Capital San Francisco","municipio_id"=>"122"],
			["nombre"=>"Sucre","municipio_id"=>"123"],
			["nombre"=>"Pecaya","municipio_id"=>"123"],
			["nombre"=>"Tucacas","municipio_id"=>"124"],
			["nombre"=>"Boca de Aroa","municipio_id"=>"124"],
			["nombre"=>"Tocópero","municipio_id"=>"125"],
			["nombre"=>"El Charal","municipio_id"=>"126"],
			["nombre"=>"Las Vegas del Tuy","municipio_id"=>"126"],
			["nombre"=>"Santa Cruz de Bucaral","municipio_id"=>"126"],
			["nombre"=>"Bruzual","municipio_id"=>"127"],
			["nombre"=>"Urumaco","municipio_id"=>"127"],
			["nombre"=>"Puerto Cumarebo","municipio_id"=>"128"],
			["nombre"=>"La Ciénaga","municipio_id"=>"128"],
			["nombre"=>"La Soledad","municipio_id"=>"128"],
			["nombre"=>"Pueblo Cumarebo","municipio_id"=>"128"],
			["nombre"=>"Zazárida","municipio_id"=>"128"],
			["nombre"=>"Camaguán","municipio_id"=>"129"],
			["nombre"=>"Puerto Miranda","municipio_id"=>"129"],
			["nombre"=>"Uverito","municipio_id"=>"129"],
			["nombre"=>"Chaguaramas","municipio_id"=>"130"],
			["nombre"=>"El Socorro","municipio_id"=>"131"],
			["nombre"=>"Valle de la Pascua","municipio_id"=>"132"],
			["nombre"=>"Espino","municipio_id"=>"132"],
			["nombre"=>"Las Mercedes","municipio_id"=>"133"],
			["nombre"=>"Cabruta","municipio_id"=>"133"],
			["nombre"=>"Santa Rita de Manapire","municipio_id"=>"133"],
			["nombre"=>"El Sombrero","municipio_id"=>"134"],
			["nombre"=>"Sosa","municipio_id"=>"134"],
			["nombre"=>"El Calvario","municipio_id"=>"135"],
			["nombre"=>"El Rastro","municipio_id"=>"135"],
			["nombre"=>"Guardatinajas","municipio_id"=>"135"],
			["nombre"=>"Capital Urbana Calabozo","municipio_id"=>"135"],
			["nombre"=>"Altagracia de Orituco","municipio_id"=>"136"],
			["nombre"=>"San Rafael de Orituco","municipio_id"=>"136"],
			["nombre"=>"San Francisco Javier de Lezama","municipio_id"=>"136"],
			["nombre"=>"Paso Real de Macaira","municipio_id"=>"136"],
			["nombre"=>"Carlos Soublette","municipio_id"=>"136"],
			["nombre"=>"San Francisco de Macaira","municipio_id"=>"136"],
			["nombre"=>"Libertad de Orituco","municipio_id"=>"136"],
			["nombre"=>"San José de Tiznados","municipio_id"=>"137"],
			["nombre"=>"San Francisco de Tiznados","municipio_id"=>"137"],
			["nombre"=>"San Lorenzo de Tiznados","municipio_id"=>"137"],
			["nombre"=>"Ortiz","municipio_id"=>"137"],
			["nombre"=>"Tucupido","municipio_id"=>"138"],
			["nombre"=>"San Rafael de Laya","municipio_id"=>"138"],
			["nombre"=>"Cantagallo","municipio_id"=>"139"],
			["nombre"=>"San Juan de los Morros","municipio_id"=>"139"],
			["nombre"=>"Parapara","municipio_id"=>"139"],
			["nombre"=>"Guayabal","municipio_id"=>"140"],
			["nombre"=>"Cazorla","municipio_id"=>"140"],
			["nombre"=>"San José de Guaribe","municipio_id"=>"141"],
			["nombre"=>"Uveral","municipio_id"=>"141"],
			["nombre"=>"Santa María de Ipire","municipio_id"=>"142"],
			["nombre"=>"Altamira","municipio_id"=>"142"],
			["nombre"=>"Unare","municipio_id"=>"143"],
			["nombre"=>"Zaraza","municipio_id"=>"143"],
			["nombre"=>"Quebrada Honda de Guache","municipio_id"=>"144"],
			["nombre"=>"Pío Tamayo","municipio_id"=>"144"],
			["nombre"=>"Yacambú","municipio_id"=>"144"],
			["nombre"=>"Freitez","municipio_id"=>"145"],
			["nombre"=>"José María Blanco","municipio_id"=>"145"],
			["nombre"=>"Catedral","municipio_id"=>"146"],
			["nombre"=>"Concepción","municipio_id"=>"146"],
			["nombre"=>"El Cují","municipio_id"=>"146"],
			["nombre"=>"Juan de Villegas","municipio_id"=>"146"],
			["nombre"=>"Santa Rosa","municipio_id"=>"146"],
			["nombre"=>"Tamaca","municipio_id"=>"146"],
			["nombre"=>"Unión","municipio_id"=>"146"],
			["nombre"=>"Aguedo Felipe Alvarado","municipio_id"=>"146"],
			["nombre"=>"Buena Vista","municipio_id"=>"146"],
			["nombre"=>"Juárez","municipio_id"=>"146"],
			["nombre"=>"Juan Bautista Rodríguez","municipio_id"=>"147"],
			["nombre"=>"Cuara","municipio_id"=>"147"],
			["nombre"=>"Diego de Lozada","municipio_id"=>"147"],
			["nombre"=>"Paraíso de San José","municipio_id"=>"147"],
			["nombre"=>"San Miguel","municipio_id"=>"147"],
			["nombre"=>"Tintorero","municipio_id"=>"147"],
			["nombre"=>"José Bernardo Dorante","municipio_id"=>"147"],
			["nombre"=>"Coronel Mariano Peraza","municipio_id"=>"147"],
			["nombre"=>"Anzoátegui","municipio_id"=>"148"],
			["nombre"=>"Bolívar","municipio_id"=>"148"],
			["nombre"=>"Guárico","municipio_id"=>"148"],
			["nombre"=>"Hilario Luna y Luna","municipio_id"=>"148"],
			["nombre"=>"Humocaro Bajo","municipio_id"=>"148"],
			["nombre"=>"Humocaro Alto","municipio_id"=>"148"],
			["nombre"=>"La Candelaria","municipio_id"=>"148"],
			["nombre"=>"Morán","municipio_id"=>"148"],
			["nombre"=>"Cabudare","municipio_id"=>"149"],
			["nombre"=>"José Gregorio Bastidas","municipio_id"=>"149"],
			["nombre"=>"Agua Viva","municipio_id"=>"149"],
			["nombre"=>"Buría","municipio_id"=>"150"],
			["nombre"=>"Gustavo Vega","municipio_id"=>"150"],
			["nombre"=>"Sarare","municipio_id"=>"150"],
			["nombre"=>"Altagracia","municipio_id"=>"151"],
			["nombre"=>"Antonio Díaz","municipio_id"=>"151"],
			["nombre"=>"Camacaro","municipio_id"=>"151"],
			["nombre"=>"Castañeda","municipio_id"=>"151"],
			["nombre"=>"Cecilio Zubillaga","municipio_id"=>"151"],
			["nombre"=>"Chiquinquira","municipio_id"=>"151"],
			["nombre"=>"El Blanco","municipio_id"=>"151"],
			["nombre"=>"Espinoza de los Monteros","municipio_id"=>"151"],
			["nombre"=>"Heriberto Arrollo","municipio_id"=>"151"],
			["nombre"=>"Lara","municipio_id"=>"151"],
			["nombre"=>"Las Mercedes","municipio_id"=>"151"],
			["nombre"=>"Manuel Morillo","municipio_id"=>"151"],
			["nombre"=>"Montaña Verde","municipio_id"=>"151"],
			["nombre"=>"Montes de Oca","municipio_id"=>"151"],
			["nombre"=>"Reyes de Vargas","municipio_id"=>"151"],
			["nombre"=>"Torres","municipio_id"=>"151"],
			["nombre"=>"Trinidad Samuel","municipio_id"=>"151"],
			["nombre"=>"Siquisique","municipio_id"=>"152"],
			["nombre"=>"San Miguel","municipio_id"=>"152"],
			["nombre"=>"Moroturo","municipio_id"=>"152"],
			["nombre"=>"Xaguas","municipio_id"=>"152"],
			["nombre"=>"Presidente Betancourt","municipio_id"=>"153"],
			["nombre"=>"Presidente Páez","municipio_id"=>"153"],
			["nombre"=>"Presidente Rómulo Gallegos","municipio_id"=>"153"],
			["nombre"=>"Gabriel Picón González","municipio_id"=>"153"],
			["nombre"=>"Héctor Amable Mora","municipio_id"=>"153"],
			["nombre"=>"José Nucete Sardi","municipio_id"=>"153"],
			["nombre"=>"Pulido Méndez","municipio_id"=>"153"],
			["nombre"=>"La Azulita","municipio_id"=>"154"],
			["nombre"=>"Santa Cruz de Mora","municipio_id"=>"155"],
			["nombre"=>"Mesa Bolívar","municipio_id"=>"155"],
			["nombre"=>"Mesa de Las Palmas","municipio_id"=>"155"],
			["nombre"=>"Aricagua","municipio_id"=>"156"],
			["nombre"=>"San Antonio","municipio_id"=>"156"],
			["nombre"=>"Canagua","municipio_id"=>"157"],
			["nombre"=>"Capurí","municipio_id"=>"157"],
			["nombre"=>"Chacantá","municipio_id"=>"157"],
			["nombre"=>"El Molino","municipio_id"=>"157"],
			["nombre"=>"Guaimaral","municipio_id"=>"157"],
			["nombre"=>"Mucutuy","municipio_id"=>"157"],
			["nombre"=>"Mucuchachí","municipio_id"=>"157"],
			["nombre"=>"Fernández Peña","municipio_id"=>"158"],
			["nombre"=>"Matriz","municipio_id"=>"158"],
			["nombre"=>"Montalbán","municipio_id"=>"158"],
			["nombre"=>"Acequias","municipio_id"=>"158"],
			["nombre"=>"Jají","municipio_id"=>"158"],
			["nombre"=>"La Mesa","municipio_id"=>"158"],
			["nombre"=>"San José del Sur","municipio_id"=>"158"],
			["nombre"=>"Tucaní","municipio_id"=>"159"],
			["nombre"=>"Florencio Ramírez","municipio_id"=>"159"],
			["nombre"=>"Santo Domingo","municipio_id"=>"160"],
			["nombre"=>"Las Piedras","municipio_id"=>"160"],
			["nombre"=>"Guaraque","municipio_id"=>"161"],
			["nombre"=>"Mesa de Quintero","municipio_id"=>"161"],
			["nombre"=>"Río Negro","municipio_id"=>"161"],
			["nombre"=>"Arapuey","municipio_id"=>"162"],
			["nombre"=>"Palmira","municipio_id"=>"162"],
			["nombre"=>"San Cristóbal de Torondoy","municipio_id"=>"163"],
			["nombre"=>"Torondoy","municipio_id"=>"163"],
			["nombre"=>"Antonio Spinetti Dini","municipio_id"=>"164"],
			["nombre"=>"Arias","municipio_id"=>"164"],
			["nombre"=>"Caracciolo Parra Pérez","municipio_id"=>"164"],
			["nombre"=>"Domingo Peña","municipio_id"=>"164"],
			["nombre"=>"El Llano","municipio_id"=>"164"],
			["nombre"=>"Gonzalo Picón Febres","municipio_id"=>"164"],
			["nombre"=>"Jacinto Plaza","municipio_id"=>"164"],
			["nombre"=>"Juan Rodríguez Suárez","municipio_id"=>"164"],
			["nombre"=>"Lasso de la Vega","municipio_id"=>"164"],
			["nombre"=>"Mariano Picón Salas","municipio_id"=>"164"],
			["nombre"=>"Milla","municipio_id"=>"164"],
			["nombre"=>"Osuna Rodríguez","municipio_id"=>"164"],
			["nombre"=>"Sagrario","municipio_id"=>"164"],
			["nombre"=>"El Morro","municipio_id"=>"164"],
			["nombre"=>"Los Nevados","municipio_id"=>"164"],
			["nombre"=>"Andrés Eloy Blanco","municipio_id"=>"165"],
			["nombre"=>"La Venta","municipio_id"=>"165"],
			["nombre"=>"Piñango","municipio_id"=>"165"],
			["nombre"=>"Timotes","municipio_id"=>"165"],
			["nombre"=>"Eloy Paredes","municipio_id"=>"166"],
			["nombre"=>"San Rafael de Alcázar","municipio_id"=>"166"],
			["nombre"=>"Santa Elena de Arenales","municipio_id"=>"166"],
			["nombre"=>"Santa María de Caparo","municipio_id"=>"167"],
			["nombre"=>"Pueblo Llano","municipio_id"=>"168"],
			["nombre"=>"Cacute","municipio_id"=>"169"],
			["nombre"=>"La Toma","municipio_id"=>"169"],
			["nombre"=>"Mucuchíes","municipio_id"=>"169"],
			["nombre"=>"Mucurubá","municipio_id"=>"169"],
			["nombre"=>"San Rafael","municipio_id"=>"169"],
			["nombre"=>"Gerónimo Maldonado","municipio_id"=>"170"],
			["nombre"=>"Bailadores","municipio_id"=>"170"],
			["nombre"=>"Tabay","municipio_id"=>"171"],
			["nombre"=>"Chiguará","municipio_id"=>"172"],
			["nombre"=>"Estánquez","municipio_id"=>"172"],
			["nombre"=>"Lagunillas","municipio_id"=>"172"],
			["nombre"=>"La Trampa","municipio_id"=>"172"],
			["nombre"=>"Pueblo Nuevo del Sur","municipio_id"=>"172"],
			["nombre"=>"San Juan","municipio_id"=>"172"],
			["nombre"=>"El Amparo","municipio_id"=>"173"],
			["nombre"=>"El Llano","municipio_id"=>"173"],
			["nombre"=>"San Francisco","municipio_id"=>"173"],
			["nombre"=>"Tovar","municipio_id"=>"173"],
			["nombre"=>"Independencia","municipio_id"=>"174"],
			["nombre"=>"María de la Concepción Palacios Blanco","municipio_id"=>"174"],
			["nombre"=>"Nueva Bolivia","municipio_id"=>"174"],
			["nombre"=>"Santa Apolonia","municipio_id"=>"174"],
			["nombre"=>"Caño El Tigre","municipio_id"=>"175"],
			["nombre"=>"Zea","municipio_id"=>"175"],
			["nombre"=>"Aragüita","municipio_id"=>"176"],
			["nombre"=>"Arévalo González","municipio_id"=>"176"],
			["nombre"=>"Capaya","municipio_id"=>"176"],
			["nombre"=>"Caucagua","municipio_id"=>"176"],
			["nombre"=>"Panaquire","municipio_id"=>"176"],
			["nombre"=>"Ribas","municipio_id"=>"176"],
			["nombre"=>"El Café","municipio_id"=>"176"],
			["nombre"=>"Marizapa","municipio_id"=>"176"],
			["nombre"=>"Cumbo","municipio_id"=>"177"],
			["nombre"=>"San José de Barlovento","municipio_id"=>"177"],
			["nombre"=>"El Cafetal","municipio_id"=>"178"],
			["nombre"=>"Las Minas","municipio_id"=>"178"],
			["nombre"=>"Nuestra Señora del Rosario","municipio_id"=>"178"],
			["nombre"=>"Higuerote","municipio_id"=>"179"],
			["nombre"=>"Curiepe","municipio_id"=>"179"],
			["nombre"=>"Tacarigua de Brión","municipio_id"=>"179"],
			["nombre"=>"Mamporal","municipio_id"=>"180"],
			["nombre"=>"Carrizal","municipio_id"=>"181"],
			["nombre"=>"Chacao","municipio_id"=>"182"],
			["nombre"=>"Charallave","municipio_id"=>"183"],
			["nombre"=>"Las Brisas","municipio_id"=>"183"],
			["nombre"=>"El Hatillo","municipio_id"=>"184"],
			["nombre"=>"Altagracia de la Montaña","municipio_id"=>"185"],
			["nombre"=>"Cecilio Acosta","municipio_id"=>"185"],
			["nombre"=>"Los Teques","municipio_id"=>"185"],
			["nombre"=>"El Jarillo","municipio_id"=>"185"],
			["nombre"=>"San Pedro.","municipio_id"=>"185"],
			["nombre"=>"Tácata","municipio_id"=>"185"],
			["nombre"=>"Paracotos","municipio_id"=>"185"],
			["nombre"=>"Cartanal","municipio_id"=>"186"],
			["nombre"=>"Santa Teresa del Tuy","municipio_id"=>"186"],
			["nombre"=>"La Democracia","municipio_id"=>"187"],
			["nombre"=>"Ocumare del Tuy","municipio_id"=>"187"],
			["nombre"=>"Santa Bárbara","municipio_id"=>"187"],
			["nombre"=>"San Antonio de los Altos","municipio_id"=>"188"],
			["nombre"=>"Río Chico","municipio_id"=>"189"],
			["nombre"=>"El Guapo","municipio_id"=>"189"],
			["nombre"=>"Tacarigua de la Laguna","municipio_id"=>"189"],
			["nombre"=>"Paparo","municipio_id"=>"189"],
			["nombre"=>"San Fernando del Guapo","municipio_id"=>"189"],
			["nombre"=>"Santa Lucía del Tuy","municipio_id"=>"190"],
			["nombre"=>"Cúpira","municipio_id"=>"191"],
			["nombre"=>"Machurucuto","municipio_id"=>"191"],
			["nombre"=>"Guarenas","municipio_id"=>"192"],
			["nombre"=>"San Antonio de Yare","municipio_id"=>"193"],
			["nombre"=>"San Francisco de Yare","municipio_id"=>"193"],
			["nombre"=>"Leoncio Martínez","municipio_id"=>"194"],
			["nombre"=>"Petare","municipio_id"=>"194"],
			["nombre"=>"Caucagüita","municipio_id"=>"194"],
			["nombre"=>"Filas de Mariche","municipio_id"=>"194"],
			["nombre"=>"La Dolorita","municipio_id"=>"194"],
			["nombre"=>"Cúa","municipio_id"=>"195"],
			["nombre"=>"Nueva Cúa","municipio_id"=>"195"],
			["nombre"=>"Guatire","municipio_id"=>"196"],
			["nombre"=>"Bolívar","municipio_id"=>"196"],
			["nombre"=>"San Antonio de Maturín","municipio_id"=>"197"],
			["nombre"=>"San Francisco de Maturín","municipio_id"=>"197"],
			["nombre"=>"Aguasay","municipio_id"=>"198"],
			["nombre"=>"Caripito","municipio_id"=>"199"],
			["nombre"=>"El Guácharo","municipio_id"=>"200"],
			["nombre"=>"La Guanota","municipio_id"=>"200"],
			["nombre"=>"Sabana de Piedra","municipio_id"=>"200"],
			["nombre"=>"San Agustín","municipio_id"=>"200"],
			["nombre"=>"Teresen","municipio_id"=>"200"],
			["nombre"=>"Caripe","municipio_id"=>"200"],
			["nombre"=>"Areo","municipio_id"=>"201"],
			["nombre"=>"Capital Cedeño","municipio_id"=>"201"],
			["nombre"=>"San Félix de Cantalicio","municipio_id"=>"201"],
			["nombre"=>"Viento Fresco","municipio_id"=>"201"],
			["nombre"=>"El Tejero","municipio_id"=>"202"],
			["nombre"=>"Punta de Mata","municipio_id"=>"202"],
			["nombre"=>"Chaguaramas","municipio_id"=>"203"],
			["nombre"=>"Las Alhuacas","municipio_id"=>"203"],
			["nombre"=>"Tabasca","municipio_id"=>"203"],
			["nombre"=>"Temblador","municipio_id"=>"203"],
			["nombre"=>"Alto de los Godos","municipio_id"=>"204"],
			["nombre"=>"Boquerón","municipio_id"=>"204"],
			["nombre"=>"Las Cocuizas","municipio_id"=>"204"],
			["nombre"=>"La Cruz","municipio_id"=>"204"],
			["nombre"=>"San Simón","municipio_id"=>"204"],
			["nombre"=>"El Corozo","municipio_id"=>"204"],
			["nombre"=>"El Furrial","municipio_id"=>"204"],
			["nombre"=>"Jusepín","municipio_id"=>"204"],
			["nombre"=>"La Pica","municipio_id"=>"204"],
			["nombre"=>"San Vicente","municipio_id"=>"204"],
			["nombre"=>"Aparicio","municipio_id"=>"205"],
			["nombre"=>"Aragua de Maturín","municipio_id"=>"205"],
			["nombre"=>"Chaguamal","municipio_id"=>"205"],
			["nombre"=>"El Pinto","municipio_id"=>"205"],
			["nombre"=>"Guanaguana","municipio_id"=>"205"],
			["nombre"=>"La Toscana","municipio_id"=>"205"],
			["nombre"=>"Taguaya","municipio_id"=>"205"],
			["nombre"=>"Cachipo","municipio_id"=>"206"],
			["nombre"=>"Quiriquire","municipio_id"=>"206"],
			["nombre"=>"Santa Bárbara","municipio_id"=>"207"],
			["nombre"=>"Barrancas","municipio_id"=>"208"],
			["nombre"=>"Los Barrancos de Fajardo","municipio_id"=>"208"],
			["nombre"=>"Uracoa","municipio_id"=>"209"],
			["nombre"=>"Antolín del Campo","municipio_id"=>"210"],
			["nombre"=>"Arismendi","municipio_id"=>"211"],
			["nombre"=>"San Juan Bautista","municipio_id"=>"212"],
			["nombre"=>"Zabala","municipio_id"=>"212"],
			["nombre"=>"García","municipio_id"=>"213"],
			["nombre"=>"Francisco Fajardo","municipio_id"=>"213"],
			["nombre"=>"Bolívar","municipio_id"=>"214"],
			["nombre"=>"Guevara","municipio_id"=>"214"],
			["nombre"=>"Cerro de Matasiete","municipio_id"=>"214"],
			["nombre"=>"Santa Ana","municipio_id"=>"214"],
			["nombre"=>"Sucre","municipio_id"=>"214"],
			["nombre"=>"Aguirre","municipio_id"=>"215"],
			["nombre"=>"Maneiro","municipio_id"=>"215"],
			["nombre"=>"Adrián","municipio_id"=>"216"],
			["nombre"=>"Juan Griego","municipio_id"=>"216"],
			["nombre"=>"Yaguaraparo","municipio_id"=>"216"],
			["nombre"=>"Porlamar","municipio_id"=>"217"],
			["nombre"=>"San Francisco de Macanao","municipio_id"=>"218"],
			["nombre"=>"Boca de Río","municipio_id"=>"218"],
			["nombre"=>"Tubores","municipio_id"=>"219"],
			["nombre"=>"Los Barales","municipio_id"=>"219"],
			["nombre"=>"Vicente Fuentes","municipio_id"=>"220"],
			["nombre"=>"Villalba","municipio_id"=>"220"],
			["nombre"=>"Agua Blanca","municipio_id"=>"221"],
			["nombre"=>"Araure","municipio_id"=>"222"],
			["nombre"=>"Río Acarigua","municipio_id"=>"222"],
			["nombre"=>"Píritu","municipio_id"=>"223"],
			["nombre"=>"Uveral","municipio_id"=>"223"],
			["nombre"=>"Cordova","municipio_id"=>"224"],
			["nombre"=>"Guanare","municipio_id"=>"224"],
			["nombre"=>"San José de la Montaña","municipio_id"=>"224"],
			["nombre"=>"San Juan de Guanaguanare","municipio_id"=>"224"],
			["nombre"=>"Virgen de Coromoto","municipio_id"=>"224"],
			["nombre"=>"Guanarito","municipio_id"=>"225"],
			["nombre"=>"Trinidad de la Capilla","municipio_id"=>"225"],
			["nombre"=>"Divina Pastora","municipio_id"=>"225"],
			["nombre"=>"Peña Blanca","municipio_id"=>"226"],
			["nombre"=>"Aparición","municipio_id"=>"227"],
			["nombre"=>"La Estación","municipio_id"=>"227"],
			["nombre"=>"Ospino","municipio_id"=>"227"],
			["nombre"=>"Acarigua","municipio_id"=>"228"],
			["nombre"=>"Payara","municipio_id"=>"228"],
			["nombre"=>"Pimpinela","municipio_id"=>"228"],
			["nombre"=>"Ramón Peraza","municipio_id"=>"228"],
			["nombre"=>"Caño Delgadito","municipio_id"=>"229"],
			["nombre"=>"Papelón","municipio_id"=>"229"],
			["nombre"=>"Antolín Tovar Anquino","municipio_id"=>"230"],
			["nombre"=>"Boconoíto","municipio_id"=>"230"],
			["nombre"=>"Santa Fé","municipio_id"=>"231"],
			["nombre"=>"San Rafael de Onoto","municipio_id"=>"231"],
			["nombre"=>"Thermo Morales","municipio_id"=>"231"],
			["nombre"=>"Florida","municipio_id"=>"232"],
			["nombre"=>"El Playón","municipio_id"=>"232"],
			["nombre"=>"Biscucuy","municipio_id"=>"233"],
			["nombre"=>"Concepción","municipio_id"=>"233"],
			["nombre"=>"San José de Saguaz","municipio_id"=>"233"],
			["nombre"=>"San Rafael de Palo Alzado","municipio_id"=>"233"],
			["nombre"=>"Uvencio Antonio Velásquez","municipio_id"=>"233"],
			["nombre"=>"Villa Rosa","municipio_id"=>"233"],
			["nombre"=>"Canelones","municipio_id"=>"234"],
			["nombre"=>"Santa Cruz","municipio_id"=>"234"],
			["nombre"=>"San Isidro Labrador","municipio_id"=>"234"],
			["nombre"=>"Mariño","municipio_id"=>"235"],
			["nombre"=>"Rómulo Gallegos","municipio_id"=>"235"],
			["nombre"=>"San José de Aerocuar","municipio_id"=>"236"],
			["nombre"=>"Tavera Acosta","municipio_id"=>"236"],
			["nombre"=>"Río Caribe","municipio_id"=>"237"],
			["nombre"=>"Antonio José de Sucre","municipio_id"=>"237"],
			["nombre"=>"El Morro de Puerto Santo","municipio_id"=>"237"],
			["nombre"=>"Puerto Santo","municipio_id"=>"237"],
			["nombre"=>"San Juan de las Galdonas","municipio_id"=>"237"],
			["nombre"=>"El Pilar","municipio_id"=>"238"],
			["nombre"=>"El Rincón","municipio_id"=>"238"],
			["nombre"=>"General Francisco Antonio Váquez","municipio_id"=>"238"],
			["nombre"=>"Guaraúnos","municipio_id"=>"238"],
			["nombre"=>"Tunapuicito","municipio_id"=>"238"],
			["nombre"=>"Unión","municipio_id"=>"238"],
			["nombre"=>"Santa Catalina","municipio_id"=>"239"],
			["nombre"=>"Santa Rosa","municipio_id"=>"239"],
			["nombre"=>"Santa Teresa","municipio_id"=>"239"],
			["nombre"=>"Bolívar","municipio_id"=>"239"],
			["nombre"=>"Maracapana","municipio_id"=>"239"],
			["nombre"=>"Libertad","municipio_id"=>"241"],
			["nombre"=>"El Paujil","municipio_id"=>"241"],
			["nombre"=>"Yaguaraparo","municipio_id"=>"241"],
			["nombre"=>"Cruz Salmerón Acosta","municipio_id"=>"242"],
			["nombre"=>"Chacopata","municipio_id"=>"242"],
			["nombre"=>"Manicuare","municipio_id"=>"242"],
			["nombre"=>"Tunapuy","municipio_id"=>"243"],
			["nombre"=>"Campo Elías","municipio_id"=>"243"],
			["nombre"=>"Irapa","municipio_id"=>"244"],
			["nombre"=>"Campo Claro","municipio_id"=>"244"],
			["nombre"=>"Maraval","municipio_id"=>"244"],
			["nombre"=>"San Antonio de Irapa","municipio_id"=>"244"],
			["nombre"=>"Soro","municipio_id"=>"244"],
			["nombre"=>"Mejía","municipio_id"=>"245"],
			["nombre"=>"Cumanacoa","municipio_id"=>"246"],
			["nombre"=>"Arenas","municipio_id"=>"246"],
			["nombre"=>"Aricagua","municipio_id"=>"246"],
			["nombre"=>"Cocollar","municipio_id"=>"246"],
			["nombre"=>"San Fernando","municipio_id"=>"246"],
			["nombre"=>"San Lorenzo","municipio_id"=>"246"],
			["nombre"=>"Villa Frontado (Muelle de Cariaco)","municipio_id"=>"247"],
			["nombre"=>"Catuaro","municipio_id"=>"247"],
			["nombre"=>"Rendón","municipio_id"=>"247"],
			["nombre"=>"San Cruz","municipio_id"=>"247"],
			["nombre"=>"Santa María","municipio_id"=>"247"],
			["nombre"=>"Altagracia Cumaná","municipio_id"=>"248"],
			["nombre"=>"Santa Inés Cumaná","municipio_id"=>"248"],
			["nombre"=>"Valentín Valiente Cumaná","municipio_id"=>"248"],
			["nombre"=>"Ayacucho Cumaná","municipio_id"=>"248"],
			["nombre"=>"San Juan","municipio_id"=>"248"],
			["nombre"=>"Raúl Leoni","municipio_id"=>"248"],
			["nombre"=>"Gran Mariscal","municipio_id"=>"248"],
			["nombre"=>"Cristóbal Colón","municipio_id"=>"249"],
			["nombre"=>"Bideau","municipio_id"=>"249"],
			["nombre"=>"Punta de Piedras","municipio_id"=>"249"],
			["nombre"=>"Güiria","municipio_id"=>"249"],
			["nombre"=>"Andrés Bello","municipio_id"=>"250"],
			["nombre"=>"Antonio Rómulo Costa","municipio_id"=>"251"],
			["nombre"=>"Ayacucho","municipio_id"=>"252"],
			["nombre"=>"Rivas Berti","municipio_id"=>"252"],
			["nombre"=>"San Pedro del Río","municipio_id"=>"252"],
			["nombre"=>"Bolívar","municipio_id"=>"253"],
			["nombre"=>"Palotal","municipio_id"=>"253"],
			["nombre"=>"General Juan Vicente Gómez","municipio_id"=>"253"],
			["nombre"=>"Isaías Medina Angarita","municipio_id"=>"253"],
			["nombre"=>"Cárdenas","municipio_id"=>"254"],
			["nombre"=>"Amenodoro Rangel Lamus","municipio_id"=>"254"],
			["nombre"=>"La Florida","municipio_id"=>"254"],
			["nombre"=>"Córdoba","municipio_id"=>"255"],
			["nombre"=>"Fernández Feo","municipio_id"=>"256"],
			["nombre"=>"Alberto Adriani","municipio_id"=>"256"],
			["nombre"=>"Santo Domingo","municipio_id"=>"256"],
			["nombre"=>"Francisco de Miranda","municipio_id"=>"257"],
			["nombre"=>"García de Hevia","municipio_id"=>"258"],
			["nombre"=>"Boca de Grita","municipio_id"=>"258"],
			["nombre"=>"José Antonio Páez","municipio_id"=>"258"],
			["nombre"=>"Guásimos","municipio_id"=>"259"],
			["nombre"=>"Independencia","municipio_id"=>"260"],
			["nombre"=>"Juan Germán Roscio","municipio_id"=>"260"],
			["nombre"=>"Román Cárdenas","municipio_id"=>"260"],
			["nombre"=>"Jáuregui","municipio_id"=>"261"],
			["nombre"=>"Emilio Constantino Guerrero","municipio_id"=>"261"],
			["nombre"=>"Monseñor Miguel Antonio Salas","municipio_id"=>"261"],
			["nombre"=>"José María Vargas","municipio_id"=>"262"],
			["nombre"=>"Junín","municipio_id"=>"263"],
			["nombre"=>"La Petrólea","municipio_id"=>"263"],
			["nombre"=>"Quinimarí","municipio_id"=>"263"],
			["nombre"=>"Bramón","municipio_id"=>"263"],
			["nombre"=>"Libertad","municipio_id"=>"264"],
			["nombre"=>"Cipriano Castro","municipio_id"=>"264"],
			["nombre"=>"Manuel Felipe Rugeles","municipio_id"=>"264"],
			["nombre"=>"Capital Libertador","municipio_id"=>"265"],
			["nombre"=>"Doradas","municipio_id"=>"265"],
			["nombre"=>"Emeterio Ochoa","municipio_id"=>"265"],
			["nombre"=>"San Joaquín de Navay","municipio_id"=>"265"],
			["nombre"=>"Lobatera","municipio_id"=>"266"],
			["nombre"=>"Constitución","municipio_id"=>"266"],
			["nombre"=>"Michelena","municipio_id"=>"267"],
			["nombre"=>"Panamericano","municipio_id"=>"268"],
			["nombre"=>"La Palmita","municipio_id"=>"268"],
			["nombre"=>"Pedro María Ureña","municipio_id"=>"269"],
			["nombre"=>"Nueva Arcadia","municipio_id"=>"269"],
			["nombre"=>"Delicias","municipio_id"=>"270"],
			["nombre"=>"Pecaya","municipio_id"=>"270"],
			["nombre"=>"Samuel Darío Maldonado","municipio_id"=>"271"],
			["nombre"=>"Boconó","municipio_id"=>"271"],
			["nombre"=>"Hernández","municipio_id"=>"271"],
			["nombre"=>"La Concordia","municipio_id"=>"272"],
			["nombre"=>"San Juan Bautista","municipio_id"=>"272"],
			["nombre"=>"Pedro María Morantes","municipio_id"=>"272"],
			["nombre"=>"San Sebastián","municipio_id"=>"272"],
			["nombre"=>"Dr. Francisco Romero Lobo","municipio_id"=>"272"],
			["nombre"=>"Seboruco","municipio_id"=>"273"],
			["nombre"=>"Simón Rodríguez","municipio_id"=>"274"],
			["nombre"=>"Sucre","municipio_id"=>"275"],
			["nombre"=>"Eleazar López Contreras","municipio_id"=>"275"],
			["nombre"=>"San Pablo","municipio_id"=>"275"],
			["nombre"=>"San José Obrero","municipio_id"=>"276"],
			["nombre"=>"San Juan Eudes","municipio_id"=>"276"],
			["nombre"=>"Uribante","municipio_id"=>"277"],
			["nombre"=>"Cárdenas","municipio_id"=>"277"],
			["nombre"=>"Juan Pablo Peñalosa","municipio_id"=>"277"],
			["nombre"=>"Potosí","municipio_id"=>"277"],
			["nombre"=>"San Judas Tadeo","municipio_id"=>"278"],
			["nombre"=>"Araguaney","municipio_id"=>"279"],
			["nombre"=>"El Jaguito","municipio_id"=>"279"],
			["nombre"=>"La Esperanza","municipio_id"=>"279"],
			["nombre"=>"Santa Isabel","municipio_id"=>"279"],
			["nombre"=>"Boconó","municipio_id"=>"280"],
			["nombre"=>"El Carmen","municipio_id"=>"280"],
			["nombre"=>"Mosquey","municipio_id"=>"280"],
			["nombre"=>"Ayacucho","municipio_id"=>"280"],
			["nombre"=>"Burbusay","municipio_id"=>"280"],
			["nombre"=>"General Ribas","municipio_id"=>"280"],
			["nombre"=>"Guaramacal","municipio_id"=>"280"],
			["nombre"=>"Vega de Guaramacal","municipio_id"=>"280"],
			["nombre"=>"Monseñor Jáuregui","municipio_id"=>"280"],
			["nombre"=>"Rafael Rangel","municipio_id"=>"280"],
			["nombre"=>"San Miguel","municipio_id"=>"280"],
			["nombre"=>"San José","municipio_id"=>"280"],
			["nombre"=>"Sabana Grande","municipio_id"=>"281"],
			["nombre"=>"Cheregüé","municipio_id"=>"281"],
			["nombre"=>"Granados","municipio_id"=>"281"],
			["nombre"=>"Arnoldo Gabaldón","municipio_id"=>"282"],
			["nombre"=>"Bolivia","municipio_id"=>"282"],
			["nombre"=>"Carrillo","municipio_id"=>"282"],
			["nombre"=>"Cegarra","municipio_id"=>"282"],
			["nombre"=>"Chejendé","municipio_id"=>"282"],
			["nombre"=>"Manuel Salvador Ulloa","municipio_id"=>"282"],
			["nombre"=>"San José","municipio_id"=>"282"],
			["nombre"=>"Carache","municipio_id"=>"283"],
			["nombre"=>"La Concepción","municipio_id"=>"283"],
			["nombre"=>"Cuicas","municipio_id"=>"283"],
			["nombre"=>"Panamericana","municipio_id"=>"283"],
			["nombre"=>"Santa Cruz","municipio_id"=>"283"],
			["nombre"=>"Escuque","municipio_id"=>"284"],
			["nombre"=>"La Unión (El Alto Escuque)","municipio_id"=>"284"],
			["nombre"=>"Santa Rita","municipio_id"=>"284"],
			["nombre"=>"Sabana Libre","municipio_id"=>"284"],
			["nombre"=>"El Socorro","municipio_id"=>"285"],
			["nombre"=>"Los Caprichos","municipio_id"=>"285"],
			["nombre"=>"Antonio José de Sucre","municipio_id"=>"285"],
			["nombre"=>"Campo Elías","municipio_id"=>"286"],
			["nombre"=>"Arnoldo Gabaldón","municipio_id"=>"286"],
			["nombre"=>"Santa Apolonia","municipio_id"=>"287"],
			["nombre"=>"El Progreso","municipio_id"=>"287"],
			["nombre"=>"La Ceiba","municipio_id"=>"287"],
			["nombre"=>"Tres de Febrero","municipio_id"=>"287"],
			["nombre"=>"El Dividive","municipio_id"=>"288"],
			["nombre"=>"Agua Santa","municipio_id"=>"288"],
			["nombre"=>"Agua Caliente","municipio_id"=>"288"],
			["nombre"=>"El Cenizo","municipio_id"=>"288"],
			["nombre"=>"Valerita","municipio_id"=>"288"],
			["nombre"=>"Monte Carmelo","municipio_id"=>"289"],
			["nombre"=>"Buena Vista","municipio_id"=>"289"],
			["nombre"=>"Santa María del Horcón","municipio_id"=>"289"],
			["nombre"=>"Motatán","municipio_id"=>"290"],
			["nombre"=>"El Baño","municipio_id"=>"290"],
			["nombre"=>"Jalisco","municipio_id"=>"290"],
			["nombre"=>"Pampán","municipio_id"=>"291"],
			["nombre"=>"Flor de Patria","municipio_id"=>"291"],
			["nombre"=>"La Paz","municipio_id"=>"291"],
			["nombre"=>"Santa Ana","municipio_id"=>"291"],
			["nombre"=>"Pampanito","municipio_id"=>"292"],
			["nombre"=>"La Concepción","municipio_id"=>"292"],
			["nombre"=>"Pampanito II","municipio_id"=>"292"],
			["nombre"=>"Betijoque","municipio_id"=>"293"],
			["nombre"=>"José Gregorio Hernández","municipio_id"=>"293"],
			["nombre"=>"La Pueblita","municipio_id"=>"293"],
			["nombre"=>"Los Cedros","municipio_id"=>"293"],
			["nombre"=>"Carvajal","municipio_id"=>"294"],
			["nombre"=>"Campo Alegre","municipio_id"=>"294"],
			["nombre"=>"Antonio Nicolás Briceño","municipio_id"=>"294"],
			["nombre"=>"José Leonardo Suárez","municipio_id"=>"294"],
			["nombre"=>"Sabana de Mendoza","municipio_id"=>"295"],
			["nombre"=>"Junín","municipio_id"=>"295"],
			["nombre"=>"Valmore Rodríguez","municipio_id"=>"295"],
			["nombre"=>"El Paraíso","municipio_id"=>"295"],
			["nombre"=>"Andrés Linares","municipio_id"=>"296"],
			["nombre"=>"Chiquinquirá","municipio_id"=>"296"],
			["nombre"=>"Cristóbal Mendoza","municipio_id"=>"296"],
			["nombre"=>"Cruz Carrillo","municipio_id"=>"296"],
			["nombre"=>"Matriz","municipio_id"=>"296"],
			["nombre"=>"Monseñor Carrillo","municipio_id"=>"296"],
			["nombre"=>"Tres Esquinas","municipio_id"=>"296"],
			["nombre"=>"Cabimbú","municipio_id"=>"297"],
			["nombre"=>"Jajó","municipio_id"=>"297"],
			["nombre"=>"La Mesa de Esnujaque","municipio_id"=>"297"],
			["nombre"=>"Santiago","municipio_id"=>"297"],
			["nombre"=>"Tuñame","municipio_id"=>"297"],
			["nombre"=>"La Quebrada","municipio_id"=>"297"],
			["nombre"=>"Juan Ignacio Montilla","municipio_id"=>"298"],
			["nombre"=>"La Beatriz","municipio_id"=>"298"],
			["nombre"=>"La Puerta","municipio_id"=>"298"],
			["nombre"=>"Mendoza del Valle de Momboy","municipio_id"=>"298"],
			["nombre"=>"Mercedes Díaz","municipio_id"=>"298"],
			["nombre"=>"San Luis","municipio_id"=>"298"],
			["nombre"=>"Caraballeda","municipio_id"=>"299"],
			["nombre"=>"Carayaca","municipio_id"=>"299"],
			["nombre"=>"Carlos Soublette","municipio_id"=>"299"],
			["nombre"=>"Caruao Chuspa","municipio_id"=>"299"],
			["nombre"=>"Catia La Mar","municipio_id"=>"299"],
			["nombre"=>"El Junko","municipio_id"=>"299"],
			["nombre"=>"La Guaira","municipio_id"=>"299"],
			["nombre"=>"Macuto","municipio_id"=>"299"],
			["nombre"=>"Maiquetía","municipio_id"=>"299"],
			["nombre"=>"Naiguatá","municipio_id"=>"299"],
			["nombre"=>"Urimare","municipio_id"=>"299"],
			["nombre"=>"Arístides Bastidas","municipio_id"=>"300"],
			["nombre"=>"Bolívar","municipio_id"=>"301"],
			["nombre"=>"Chivacoa","municipio_id"=>"302"],
			["nombre"=>"Campo Elías","municipio_id"=>"302"],
			["nombre"=>"Cocorote","municipio_id"=>"303"],
			["nombre"=>"Independencia","municipio_id"=>"304"],
			["nombre"=>"José Antonio Páez","municipio_id"=>"305"],
			["nombre"=>"La Trinidad","municipio_id"=>"306"],
			["nombre"=>"Manuel Monge","municipio_id"=>"307"],
			["nombre"=>"Salóm","municipio_id"=>"308"],
			["nombre"=>"Temerla","municipio_id"=>"308"],
			["nombre"=>"Nirgua","municipio_id"=>"308"],
			["nombre"=>"San Andrés","municipio_id"=>"309"],
			["nombre"=>"Yaritagua","municipio_id"=>"309"],
			["nombre"=>"San Javier","municipio_id"=>"310"],
			["nombre"=>"Albarico","municipio_id"=>"310"],
			["nombre"=>"San Felipe","municipio_id"=>"310"],
			["nombre"=>"Sucre","municipio_id"=>"311"],
			["nombre"=>"Urachiche","municipio_id"=>"312"],
			["nombre"=>"El Guayabo","municipio_id"=>"313"],
			["nombre"=>"Farriar","municipio_id"=>"313"],
			["nombre"=>"Isla de Toas","municipio_id"=>"314"],
			["nombre"=>"Monagas","municipio_id"=>"314"],
			["nombre"=>"General Urdaneta","municipio_id"=>"315"],
			["nombre"=>"Libertador","municipio_id"=>"315"],
			["nombre"=>"Marcelino Briceño","municipio_id"=>"315"],
			["nombre"=>"Pueblo Nuevo","municipio_id"=>"315"],
			["nombre"=>"Manuel Guanipa Matos","municipio_id"=>"315"],
			["nombre"=>"Ambrosio","municipio_id"=>"316"],
			["nombre"=>"Carmen Herrera","municipio_id"=>"316"],
			["nombre"=>"La Rosa","municipio_id"=>"316"],
			["nombre"=>"Germán Ríos Linares","municipio_id"=>"316"],
			["nombre"=>"San Benito","municipio_id"=>"316"],
			["nombre"=>"Rómulo Betancourt","municipio_id"=>"316"],
			["nombre"=>"Jorge Hernández","municipio_id"=>"316"],
			["nombre"=>"Punta Gorda","municipio_id"=>"316"],
			["nombre"=>"Arístides Calvani","municipio_id"=>"316"],
			["nombre"=>"Encontrados","municipio_id"=>"317"],
			["nombre"=>"Udón Pérez","municipio_id"=>"317"],
			["nombre"=>"Moralito","municipio_id"=>"318"],
			["nombre"=>"San Carlos del Zulia","municipio_id"=>"318"],
			["nombre"=>"Santa Cruz del Zulia","municipio_id"=>"318"],
			["nombre"=>"Santa Bárbara","municipio_id"=>"318"],
			["nombre"=>"Urribarrí","municipio_id"=>"318"],
			["nombre"=>"Carlos Quevedo","municipio_id"=>"319"],
			["nombre"=>"Francisco Javier Pulgar","municipio_id"=>"319"],
			["nombre"=>"Simón Rodríguez","municipio_id"=>"319"],
			["nombre"=>"Guamo-Gavilanes","municipio_id"=>"319"],
			["nombre"=>"Sinamaica","municipio_id"=>"320"],
			["nombre"=>"Alta Guajira","municipio_id"=>"320"],
			["nombre"=>"Elías Sánchez Rubio","municipio_id"=>"320"],
			["nombre"=>"Guajira","municipio_id"=>"320"],
			["nombre"=>"La Concepción","municipio_id"=>"321"],
			["nombre"=>"San José","municipio_id"=>"321"],
			["nombre"=>"Mariano Parra León","municipio_id"=>"321"],
			["nombre"=>"José Ramón Yépez","municipio_id"=>"321"],
			["nombre"=>"Jesús María Semprún","municipio_id"=>"322"],
			["nombre"=>"Barí","municipio_id"=>"322"],
			["nombre"=>"Concepción","municipio_id"=>"323"],
			["nombre"=>"Andrés Bello","municipio_id"=>"323"],
			["nombre"=>"Chiquinquirá","municipio_id"=>"323"],
			["nombre"=>"El Carmelo","municipio_id"=>"323"],
			["nombre"=>"Potreritos","municipio_id"=>"323"],
			["nombre"=>"Libertad","municipio_id"=>"324"],
			["nombre"=>"Alonso de Ojeda","municipio_id"=>"324"],
			["nombre"=>"Venezuela","municipio_id"=>"324"],
			["nombre"=>"Eleazar López Contreras","municipio_id"=>"324"],
			["nombre"=>"Campo Lara","municipio_id"=>"324"],
			["nombre"=>"Bartolomé de las Casas","municipio_id"=>"325"],
			["nombre"=>"Libertad","municipio_id"=>"325"],
			["nombre"=>"Río Negro","municipio_id"=>"325"],
			["nombre"=>"San José de Perijá","municipio_id"=>"325"],
			["nombre"=>"San Rafael","municipio_id"=>"326"],
			["nombre"=>"La Sierrita","municipio_id"=>"326"],
			["nombre"=>"Las Parcelas","municipio_id"=>"326"],
			["nombre"=>"Luis de Vicente","municipio_id"=>"326"],
			["nombre"=>"Monseñor Marcos Sergio Godoy","municipio_id"=>"326"],
			["nombre"=>"Ricaurte","municipio_id"=>"326"],
			["nombre"=>"Tamare","municipio_id"=>"326"],
			["nombre"=>"Antonio Borjas Romero","municipio_id"=>"327"],
			["nombre"=>"Bolívar","municipio_id"=>"327"],
			["nombre"=>"Cacique Mara","municipio_id"=>"327"],
			["nombre"=>"Carracciolo Parra Pérez","municipio_id"=>"327"],
			["nombre"=>"Cecilio Acosta","municipio_id"=>"327"],
			["nombre"=>"Cristo de Aranza","municipio_id"=>"327"],
			["nombre"=>"Coquivacoa","municipio_id"=>"327"],
			["nombre"=>"Chiquinquirá","municipio_id"=>"327"],
			["nombre"=>"Francisco Eugenio Bustamante","municipio_id"=>"327"],
			["nombre"=>"Idelfonzo Vásquez","municipio_id"=>"327"],
			["nombre"=>"Juana de Ávila","municipio_id"=>"327"],
			["nombre"=>"Luis Hurtado Higuera","municipio_id"=>"327"],
			["nombre"=>"Manuel Dagnino","municipio_id"=>"327"],
			["nombre"=>"Olegario Villalobos.","municipio_id"=>"327"],
			["nombre"=>"Raúl Leoni","municipio_id"=>"327"],
			["nombre"=>"Santa Lucía","municipio_id"=>"327"],
			["nombre"=>"Venancio Pulgar","municipio_id"=>"327"],
			["nombre"=>"San Isidro","municipio_id"=>"327"],
			["nombre"=>"Altagracia","municipio_id"=>"328"],
			["nombre"=>"Faría","municipio_id"=>"328"],
			["nombre"=>"Ana María Campos","municipio_id"=>"328"],
			["nombre"=>"San Antonio","municipio_id"=>"328"],
			["nombre"=>"San José","municipio_id"=>"328"],
			["nombre"=>"Donaldo García","municipio_id"=>"329"],
			["nombre"=>"El Rosario","municipio_id"=>"329"],
			["nombre"=>"Sixto Zambrano","municipio_id"=>"329"],
			["nombre"=>"San Francisco","municipio_id"=>"330"],
			["nombre"=>"El Bajo","municipio_id"=>"330"],
			["nombre"=>"Domitila Flores","municipio_id"=>"330"],
			["nombre"=>"Francisco Ochoa","municipio_id"=>"330"],
			["nombre"=>"Los Cortijos","municipio_id"=>"330"],
			["nombre"=>"Marcial Hernández","municipio_id"=>"330"],
			["nombre"=>"Santa Rita","municipio_id"=>"331"],
			["nombre"=>"El Mene","municipio_id"=>"331"],
			["nombre"=>"Pedro Lucas Urribarrí","municipio_id"=>"331"],
			["nombre"=>"José Cenobio Urribarrí","municipio_id"=>"331"],
			["nombre"=>"Rafael Maria Baralt","municipio_id"=>"332"],
			["nombre"=>"Manuel Manrique","municipio_id"=>"332"],
			["nombre"=>"Rafael Urdaneta","municipio_id"=>"332"],
			["nombre"=>"Bobures","municipio_id"=>"333"],
			["nombre"=>"Gibraltar","municipio_id"=>"333"],
			["nombre"=>"Heras","municipio_id"=>"333"],
			["nombre"=>"Monseñor Arturo Álvarez","municipio_id"=>"333"],
			["nombre"=>"Rómulo Gallegos","municipio_id"=>"333"],
			["nombre"=>"El Batey","municipio_id"=>"333"],
			["nombre"=>"Rafael Urdaneta","municipio_id"=>"334"],
			["nombre"=>"La Victoria","municipio_id"=>"334"],
			["nombre"=>"Raúl Cuenca","municipio_id"=>"334"],
			["nombre"=>"23 de enero","municipio_id"=>"335"],
			["nombre"=>"Altagracia","municipio_id"=>"335"],
			["nombre"=>"Antímano","municipio_id"=>"335"],
			["nombre"=>"Caricuao","municipio_id"=>"335"],
			["nombre"=>"Catedral","municipio_id"=>"335"],
			["nombre"=>"Coche","municipio_id"=>"335"],
			["nombre"=>"El Junquito","municipio_id"=>"335"],
			["nombre"=>"El Paraíso","municipio_id"=>"335"],
			["nombre"=>"El Recreo","municipio_id"=>"335"],
			["nombre"=>"El Valle","municipio_id"=>"335"],
			["nombre"=>"Candelaria","municipio_id"=>"335"],
			["nombre"=>"La Pastora","municipio_id"=>"335"],
			["nombre"=>"La Vega","municipio_id"=>"335"],
			["nombre"=>"Macarao","municipio_id"=>"335"],
			["nombre"=>"San Agustín","municipio_id"=>"335"],
			["nombre"=>"San Bernardino","municipio_id"=>"335"],
			["nombre"=>"San José","municipio_id"=>"335"],
			["nombre"=>"San Juan","municipio_id"=>"335"],
			["nombre"=>"San Pedro","municipio_id"=>"335"],
			["nombre"=>"Santa Rosalía","municipio_id"=>"335"],
			["nombre"=>"Santa Teresa","municipio_id"=>"335"],
			["nombre"=>"Sucre (Catia)","municipio_id"=>"335"]
			["nombre"=>"No encontrado","municipio_id"=>"336"]
        ];	

        foreach ($filas as $fila){
	        Parroquia::create($fila);
        }
    }
}
